rails g scaffold osts_type name
rails g scaffold osts_plateforme name
rails g scaffold osts_plateforme name
rails g scaffold osts_monnaie name
rails g scaffold osts_role name
rails g scaffold osts_people name
rails g scaffold osts_role name
rails g scaffold osts_people name
rails g scaffold osts_labels name
rails g scaffold osts_labels name
rails g scaffold osts_distributeurs name
rails g scaffold osts_distributeurs name
rails g scaffold osts_groupes name
rails g scaffold osts_anime name
rails g scaffold osts_ln name
rails g scaffold osts_drama name
rails g scaffold osts_am name
rails g scaffold osts_jv name
rails g scaffold osts_ost name
rails g scaffold osts_emission_tv name
rails g scaffold osts titre:string titre_original_latin:string titre_original:string titre_us:string titre_alternatif:string osts_type_id:integer osts_plateforme_id:integer osts_plateforme_id:integer ref:string date_jj:string date_mm:string date_aaaa:string prix:string osts_monnaie_id:integer bonus_cd:string osts_role_id:integer osts_people_id:integer osts_role_id:integer osts_people_id:integer image:string sametracklist:string osts_labels_id:integer osts_labels_id:integer osts_distributeurs_id:integer osts_distributeurs_id:integer infos:text osts_groupes_id:integer osts_anime_id:integer osts_ln_id:integer osts_drama_id:integer osts_am_id:integer osts_jv_id:integer osts_ost_id:integer osts_emission_tv_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold animes_format name
rails g scaffold animes_origine name
rails g scaffold animes_encours name
rails g scaffold animes_pays name
rails g scaffold animes_pays name
rails g scaffold animes_genres name
rails g scaffold animes_genres name
rails g scaffold animes_themes name
rails g scaffold animes_themes name
rails g scaffold animes_staff_role name
rails g scaffold animes_staff_people name
rails g scaffold animes_staff_role name
rails g scaffold animes_staff_people name
rails g scaffold animes_societe_role name
rails g scaffold animes_societe_people name
rails g scaffold animes_societe_role name
rails g scaffold animes_societe_people name
rails g scaffold animes_public_averti name
rails g scaffold animes_editeurs_vf_role name
rails g scaffold animes_editeurs_vf name
rails g scaffold animes_editeurs_vf_role name
rails g scaffold animes_editeurs_vf name
rails g scaffold animes_groupes name
rails g scaffold animes_actualite name
rails g scaffold animes_actualite_mini name
rails g scaffold animes_anime name
rails g scaffold animes_anime_plus name
rails g scaffold animes_ln name
rails g scaffold animes_ln_plus name
rails g scaffold animes_manga name
rails g scaffold animes_manga_plus name
rails g scaffold animes_jv name
rails g scaffold animes_jv_plus name
rails g scaffold animes_am name
rails g scaffold animes_am_plus name
rails g scaffold animes_drama name
rails g scaffold animes_drama_plus name
rails g scaffold animes_people name
rails g scaffold animes_dvd name
rails g scaffold animes_artbook name
rails g scaffold animes_photobook name
rails g scaffold animes_litterature_asiatique name
rails g scaffold animes_litterature_asiatique_plus name
rails g scaffold animes_culture name
rails g scaffold animes_ost name
rails g scaffold animes_cd name
rails g scaffold animes_doujin name
rails g scaffold animes_amv name
rails g scaffold animes_cinema name
rails g scaffold animes_quizz name
rails g scaffold animes_topic name
rails g scaffold animes titre:string titre_alternatif:string titre_alternatif_suite:string titre_original_latin:string titre_original:string image:string animes_format_id:integer animes_origine_id:integer webanime:string animes_encours_id:integer date_debut_jj:string date_debut_mm:string date_debut_aaaa:string date_fin_jj:string date_fin_mm:string date_fin_aaaa:string animes_pays_id:integer animes_pays_id:integer animes_genres_id:integer animes_genres_id:integer animes_themes_id:integer animes_themes_id:integer animes_staff_role_id:integer animes_staff_people_id:integer animes_staff_role_id:integer animes_staff_people_id:integer animes_societe_role_id:integer animes_societe_people_id:integer animes_societe_role_id:integer animes_societe_people_id:integer animes_public_averti_id:integer age:string nb_ep:string total_ep_inconnu:string duree:string licencie:string licencie:string animes_editeurs_vf_role_id:integer animes_editeurs_vf_id:integer animes_editeurs_vf_role_id:integer animes_editeurs_vf_id:integer date_debut_simulcast_jj:string date_debut_simulcast_mm:string date_debut_simulcast_aaaa:string date_vf_jj:string date_vf_mm:string date_vf_aaaa:string image_francaise:string description:text site:string site2:string youtube:string animes_groupes_id:integer animes_actualite_id:integer animes_actualite_mini_id:integer animes_anime_id:integer animes_anime_plus_id:integer animes_ln_id:integer animes_ln_plus_id:integer animes_manga_id:integer animes_manga_plus_id:integer animes_jv_id:integer animes_jv_plus_id:integer animes_am_id:integer animes_am_plus_id:integer animes_drama_id:integer animes_drama_plus_id:integer animes_people_id:integer animes_dvd_id:integer animes_artbook_id:integer animes_photobook_id:integer animes_litterature_asiatique_id:integer animes_litterature_asiatique_plus_id:integer animes_culture_id:integer animes_ost_id:integer animes_cd_id:integer animes_doujin_id:integer animes_amv_id:integer animes_cinema_id:integer animes_quizz_id:integer animes_topic_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold evènements_pays name
rails g scaffold evènements_people name
rails g scaffold evènements titre:string description:text date:string date_fin:string heure:string prix:string ville:string lieu:string adresse:string evènements_pays_id:integer lien:string site:string evènements_people_id:integer acceptregles:string
rails g scaffold artbooks_france name
rails g scaffold artbooks_pays name
rails g scaffold artbooks_illustrations name
rails g scaffold artbooks_type name
rails g scaffold artbooks_editeurs_vo name
rails g scaffold artbooks_editeurs_vo name
rails g scaffold artbooks_editeurs_vf name
rails g scaffold artbooks_editeurs_vf name
rails g scaffold artbooks_role name
rails g scaffold artbooks_people name
rails g scaffold artbooks_role name
rails g scaffold artbooks_people name
rails g scaffold artbooks_societe_role name
rails g scaffold artbooks_societe_people name
rails g scaffold artbooks_societe_role name
rails g scaffold artbooks_societe_people name
rails g scaffold artbooks_public_averti name
rails g scaffold artbooks_groupes name
rails g scaffold artbooks_anime name
rails g scaffold artbooks_manga name
rails g scaffold artbooks_ln name
rails g scaffold artbooks_doujinshi name
rails g scaffold artbooks_jv name
rails g scaffold artbooks_drama name
rails g scaffold artbooks_am name
rails g scaffold artbooks_litterature_asiatique name
rails g scaffold artbooks_artbook name
rails g scaffold artbooks_goodies name
rails g scaffold artbooks_doujin name
rails g scaffold artbooks_actualite name
rails g scaffold artbooks_actualite_mini name
rails g scaffold artbooks_culture name
rails g scaffold artbooks artbooks_france_id:integer artbooks_pays_id:integer titre:string titre_alternatif:string titre_original_latin:string titre_original:string image:string image_vo:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string prix:string ean:string nb_pages:string artbooks_illustrations_id:integer artbooks_type_id:integer crossover:string artbooks_editeurs_vo_id:integer artbooks_editeurs_vo_id:integer artbooks_editeurs_vf_id:integer artbooks_editeurs_vf_id:integer artbooks_role_id:integer artbooks_people_id:integer artbooks_role_id:integer artbooks_people_id:integer artbooks_societe_role_id:integer artbooks_societe_people_id:integer artbooks_societe_role_id:integer artbooks_societe_people_id:integer resume:text infos:text artbooks_public_averti_id:integer artbooks_groupes_id:integer artbooks_anime_id:integer artbooks_manga_id:integer artbooks_ln_id:integer artbooks_doujinshi_id:integer artbooks_jv_id:integer artbooks_drama_id:integer artbooks_am_id:integer artbooks_litterature_asiatique_id:integer artbooks_artbook_id:integer artbooks_goodies_id:integer artbooks_doujin_id:integer artbooks_actualite_id:integer artbooks_actualite_mini_id:integer artbooks_culture_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _cds_type name
rails g scaffold _cds_monnaie name
rails g scaffold _cds_role name
rails g scaffold _cds_people name
rails g scaffold _cds_role name
rails g scaffold _cds_people name
rails g scaffold _cds_labels name
rails g scaffold _cds_labels name
rails g scaffold _cds_distributeurs name
rails g scaffold _cds_distributeurs name
rails g scaffold _cds_groupes name
rails g scaffold _cds_cd name
rails g scaffold _cds_anime name
rails g scaffold _cds_ln name
rails g scaffold _cds_drama name
rails g scaffold _cds_am name
rails g scaffold _cds_jv name
rails g scaffold _cds_emission_tv name
rails g scaffold _cds_bonus name
rails g scaffold _cds_manga name
rails g scaffold _cds titre:string titre_original:string titre_original_latin:string _cds_type_id:integer ref:string date_jj:string date_mm:string date_aaaa:string prix:string _cds_monnaie_id:integer _cds_role_id:integer _cds_people_id:integer _cds_role_id:integer _cds_people_id:integer image:string sametracklist:string _cds_labels_id:integer _cds_labels_id:integer _cds_distributeurs_id:integer _cds_distributeurs_id:integer infos:text _cds_groupes_id:integer _cds_cd_id:integer _cds_anime_id:integer _cds_ln_id:integer _cds_drama_id:integer _cds_am_id:integer _cds_jv_id:integer _cds_emission_tv_id:integer _cds_bonus_id:integer _cds_manga_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _dvd_/_blu_rays_france name
rails g scaffold _dvd_/_blu_rays_pays name
rails g scaffold _dvd_/_blu_rays_format name
rails g scaffold _dvd_/_blu_rays_type_edition name
rails g scaffold _dvd_/_blu_rays_editeurs name
rails g scaffold _dvd_/_blu_rays_editeurs name
rails g scaffold _dvd_/_blu_rays_public_averti name
rails g scaffold _dvd_/_blu_rays_groupes name
rails g scaffold _dvd_/_blu_rays_anime name
rails g scaffold _dvd_/_blu_rays_drama name
rails g scaffold _dvd_/_blu_rays_am name
rails g scaffold _dvd_/_blu_rays_litterature_asiatique name
rails g scaffold _dvd_/_blu_rays_jv name
rails g scaffold _dvd_/_blu_rays_people name
rails g scaffold _dvd_/_blu_rays_emission_tv name
rails g scaffold _dvd_/_blu_rays_actualite name
rails g scaffold _dvd_/_blu_rays_actualite_mini name
rails g scaffold _dvd_/_blu_rays type:string type:string type:string type:string type:string type:string _dvd_/_blu_rays_france_id:integer _dvd_/_blu_rays_pays_id:integer titre:string titre_alternatif:string titre_original:string image:string date_parution_jj:string date_parution_mm:string date_parution_aaaa:string prix:string ean:string ref:string _dvd_/_blu_rays_format_id:integer _dvd_/_blu_rays_type_edition_id:integer _dvd_/_blu_rays_editeurs_id:integer _dvd_/_blu_rays_editeurs_id:integer audiodescription:string duree:string nb_disque:string resume:text episodes:text infos:text youtube:string _dvd_/_blu_rays_public_averti_id:integer _dvd_/_blu_rays_groupes_id:integer _dvd_/_blu_rays_anime_id:integer _dvd_/_blu_rays_drama_id:integer _dvd_/_blu_rays_am_id:integer _dvd_/_blu_rays_litterature_asiatique_id:integer _dvd_/_blu_rays_jv_id:integer _dvd_/_blu_rays_people_id:integer _dvd_/_blu_rays_emission_tv_id:integer _dvd_/_blu_rays_actualite_id:integer _dvd_/_blu_rays_actualite_mini_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _goodies_type name
rails g scaffold _goodies_pays name
rails g scaffold _goodies_matiere name
rails g scaffold _goodies_matiere name
rails g scaffold _goodies_editeurs_vo name
rails g scaffold _goodies_editeurs_vo name
rails g scaffold _goodies_editeurs_vf name
rails g scaffold _goodies_editeurs_vf name
rails g scaffold _goodies_staff_role name
rails g scaffold _goodies_staff_people name
rails g scaffold _goodies_staff_role name
rails g scaffold _goodies_staff_people name
rails g scaffold _goodies_societe_role name
rails g scaffold _goodies_societe_people name
rails g scaffold _goodies_societe_role name
rails g scaffold _goodies_societe_people name
rails g scaffold _goodies_public_averti name
rails g scaffold _goodies_groupes name
rails g scaffold _goodies_anime name
rails g scaffold _goodies_perso name
rails g scaffold _goodies_manga name
rails g scaffold _goodies_perso_manga name
rails g scaffold _goodies_jv name
rails g scaffold _goodies_jv_perso name
rails g scaffold _goodies_ln name
rails g scaffold _goodies_drama name
rails g scaffold _goodies_am name
rails g scaffold _goodies_artbook name
rails g scaffold _goodies_photobook name
rails g scaffold _goodies_doujinshi name
rails g scaffold _goodies_dvd name
rails g scaffold _goodies_cd name
rails g scaffold _goodies_ost name
rails g scaffold _goodies_people name
rails g scaffold _goodies_goodies name
rails g scaffold _goodies_clip name
rails g scaffold _goodies_bonus name
rails g scaffold _goodies_litterature_asiatique name
rails g scaffold _goodies_actualite name
rails g scaffold _goodies_actualite_mini name
rails g scaffold _goodies _goodies_type_id:integer _goodies_pays_id:integer titre:string titre_alternatif:string titre_original_latin:string titre_original:string image:string image_vo:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string date_reedition_jj:string date_reedition_mm:string date_reedition_aaaa:string prix:string commerce:string ean:string ref:string _goodies_matiere_id:integer _goodies_matiere_id:integer dimensions_h:string dimensions_w:string dimensions_z:string poids:string echelle:string articule:string articule:string site:string _goodies_editeurs_vo_id:integer _goodies_editeurs_vo_id:integer _goodies_editeurs_vf_id:integer _goodies_editeurs_vf_id:integer _goodies_staff_role_id:integer _goodies_staff_people_id:integer _goodies_staff_role_id:integer _goodies_staff_people_id:integer sculpteur:string _goodies_societe_role_id:integer _goodies_societe_people_id:integer _goodies_societe_role_id:integer _goodies_societe_people_id:integer resume:text infos:text youtube:string _goodies_public_averti_id:integer _goodies_groupes_id:integer _goodies_anime_id:integer _goodies_perso_id:integer _goodies_manga_id:integer _goodies_perso_manga_id:integer _goodies_jv_id:integer _goodies_jv_perso_id:integer _goodies_ln_id:integer _goodies_drama_id:integer _goodies_am_id:integer _goodies_artbook_id:integer _goodies_photobook_id:integer _goodies_doujinshi_id:integer _goodies_dvd_id:integer _goodies_cd_id:integer _goodies_ost_id:integer _goodies_people_id:integer _goodies_goodies_id:integer _goodies_clip_id:integer _goodies_bonus_id:integer _goodies_litterature_asiatique_id:integer _goodies_actualite_id:integer _goodies_actualite_mini_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _photobooks_france name
rails g scaffold _photobooks_pays name
rails g scaffold _photobooks_disponibilite name
rails g scaffold _photobooks_illustrations name
rails g scaffold _photobooks_type name
rails g scaffold _photobooks_editeurs_vo name
rails g scaffold _photobooks_editeurs_vo name
rails g scaffold _photobooks_editeurs_vf name
rails g scaffold _photobooks_editeurs_vf name
rails g scaffold _photobooks_role name
rails g scaffold _photobooks_people name
rails g scaffold _photobooks_role name
rails g scaffold _photobooks_people name
rails g scaffold _photobooks_societe_role name
rails g scaffold _photobooks_societe_people name
rails g scaffold _photobooks_societe_role name
rails g scaffold _photobooks_societe_people name
rails g scaffold _photobooks_public_averti name
rails g scaffold _photobooks_groupes name
rails g scaffold _photobooks_drama name
rails g scaffold _photobooks_am name
rails g scaffold _photobooks_cd name
rails g scaffold _photobooks_photobook name
rails g scaffold _photobooks_anime name
rails g scaffold _photobooks_bonus name
rails g scaffold _photobooks_actualite name
rails g scaffold _photobooks_actualite_mini name
rails g scaffold _photobooks_goodies name
rails g scaffold _photobooks _photobooks_france_id:integer _photobooks_pays_id:integer titre:string titre_alternatif:string titre_original_latin:string titre_original:string image:string image_vo:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string prix:string ean:string ref:string _photobooks_disponibilite_id:integer nb_pages:string site:string _photobooks_illustrations_id:integer _photobooks_type_id:integer _photobooks_editeurs_vo_id:integer _photobooks_editeurs_vo_id:integer _photobooks_editeurs_vf_id:integer _photobooks_editeurs_vf_id:integer _photobooks_role_id:integer _photobooks_people_id:integer _photobooks_role_id:integer _photobooks_people_id:integer _photobooks_societe_role_id:integer _photobooks_societe_people_id:integer _photobooks_societe_role_id:integer _photobooks_societe_people_id:integer resume:text infos:text _photobooks_public_averti_id:integer _photobooks_groupes_id:integer _photobooks_drama_id:integer _photobooks_am_id:integer _photobooks_cd_id:integer _photobooks_photobook_id:integer _photobooks_anime_id:integer _photobooks_bonus_id:integer _photobooks_actualite_id:integer _photobooks_actualite_mini_id:integer _photobooks_goodies_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _boutiques_pays name
rails g scaffold _boutiques nom:string image:string adresse:text tel:string description:text dept:string ville:string _boutiques_pays_id:integer site:string acceptregles:string
rails g scaffold _brèves_cat name
rails g scaffold _brèves_actualite name
rails g scaffold _brèves_actualite_mini name
rails g scaffold _brèves_people name
rails g scaffold _brèves_anime name
rails g scaffold _brèves_ln name
rails g scaffold _brèves_manga name
rails g scaffold _brèves_drama name
rails g scaffold _brèves_am name
rails g scaffold _brèves_litterature_asiatique name
rails g scaffold _brèves_livre_jeunesse name
rails g scaffold _brèves_magazine name
rails g scaffold _brèves_beau_livre name
rails g scaffold _brèves_jv name
rails g scaffold _brèves_dvd name
rails g scaffold _brèves_artbook name
rails g scaffold _brèves_photobook name
rails g scaffold _brèves_goodies name
rails g scaffold _brèves_cinema name
rails g scaffold _brèves_evenement name
rails g scaffold _brèves_concerts name
rails g scaffold _brèves_recette name
rails g scaffold _brèves_cd name
rails g scaffold _brèves_ost name
rails g scaffold _brèves_amv name
rails g scaffold _brèves_clip name
rails g scaffold _brèves_emission_tv name
rails g scaffold _brèves_emission_tv_numero name
rails g scaffold _brèves_sondage name
rails g scaffold _brèves_quizz name
rails g scaffold _brèves_concours name
rails g scaffold _brèves_manga_editeur name
rails g scaffold _brèves_anime_studio name
rails g scaffold _brèves_jv_societe name
rails g scaffold _brèves_societe name
rails g scaffold _brèves_culture name
rails g scaffold _brèves titre:string _brèves_cat_id:integer image:string texte:text tags:string source:string source_url:string source2:string source2_url:string source3:string source3_url:string _brèves_actualite_id:integer _brèves_actualite_mini_id:integer _brèves_people_id:integer _brèves_anime_id:integer _brèves_ln_id:integer _brèves_manga_id:integer _brèves_drama_id:integer _brèves_am_id:integer _brèves_litterature_asiatique_id:integer _brèves_livre_jeunesse_id:integer _brèves_magazine_id:integer _brèves_beau_livre_id:integer _brèves_jv_id:integer _brèves_dvd_id:integer _brèves_artbook_id:integer _brèves_photobook_id:integer _brèves_goodies_id:integer _brèves_cinema_id:integer _brèves_evenement_id:integer _brèves_concerts_id:integer _brèves_recette_id:integer _brèves_cd_id:integer _brèves_ost_id:integer _brèves_amv_id:integer _brèves_clip_id:integer _brèves_emission_tv_id:integer _brèves_emission_tv_numero_id:integer _brèves_sondage_id:integer _brèves_quizz_id:integer _brèves_concours_id:integer _brèves_manga_editeur_id:integer _brèves_anime_studio_id:integer _brèves_jv_societe_id:integer _brèves_societe_id:integer _brèves_culture_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _clips_/_lives_/_bonus_/_concerts_type name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_type_bonus name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_role name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_people name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_role name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_people name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_clip name
rails g scaffold _clips_/_lives_/_bonus_/_concerts_emission_tv_numero name
rails g scaffold _clips_/_lives_/_bonus_/_concerts _clips_/_lives_/_bonus_/_concerts_type_id:integer _clips_/_lives_/_bonus_/_concerts_type_bonus_id:integer titre:string titre_original:string date_jj:string date_mm:string date_aaaa:string _clips_/_lives_/_bonus_/_concerts_role_id:integer _clips_/_lives_/_bonus_/_concerts_people_id:integer _clips_/_lives_/_bonus_/_concerts_role_id:integer _clips_/_lives_/_bonus_/_concerts_people_id:integer image:string youtube:string infos:text _clips_/_lives_/_bonus_/_concerts_clip_id:integer _clips_/_lives_/_bonus_/_concerts_emission_tv_numero_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _concerts_artiste name
rails g scaffold _concerts_pays name
rails g scaffold _concerts date:string _concerts_artiste_id:integer nom:string endroit:string adresse:string ville:string _concerts_pays_id:integer infos:text lien:string prix:string heure:string acceptregles:string
rails g scaffold _doujins_conventions name
rails g scaffold _doujins_conventions name
rails g scaffold _doujins_role name
rails g scaffold _doujins_people name
rails g scaffold _doujins_role name
rails g scaffold _doujins_people name
rails g scaffold _doujins_genres name
rails g scaffold _doujins_genres name
rails g scaffold _doujins_groupes name
rails g scaffold _doujins_anime name
rails g scaffold _doujins_ln name
rails g scaffold _doujins_drama name
rails g scaffold _doujins_am name
rails g scaffold _doujins_jv name
rails g scaffold _doujins_doujin name
rails g scaffold _doujins_artbook name
rails g scaffold _doujins titre:string titre_original_latin:string titre_original:string titre_alternatif:string _doujins_conventions_id:integer _doujins_conventions_id:integer ref:string date_jj:string date_mm:string date_aaaa:string _doujins_role_id:integer _doujins_people_id:integer _doujins_role_id:integer _doujins_people_id:integer cercle:string image:string infos:text _doujins_genres_id:integer _doujins_genres_id:integer _doujins_groupes_id:integer _doujins_anime_id:integer _doujins_ln_id:integer _doujins_drama_id:integer _doujins_am_id:integer _doujins_jv_id:integer _doujins_doujin_id:integer _doujins_artbook_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _doujinshis_france name
rails g scaffold _doujinshis_origine name
rails g scaffold _doujinshis_pays name
rails g scaffold _doujinshis_pays name
rails g scaffold _doujinshis_type name
rails g scaffold _doujinshis_genres name
rails g scaffold _doujinshis_genres name
rails g scaffold _doujinshis_themes name
rails g scaffold _doujinshis_themes name
rails g scaffold _doujinshis_genres_averti name
rails g scaffold _doujinshis_genres_averti name
rails g scaffold _doujinshis_conventions name
rails g scaffold _doujinshis_conventions name
rails g scaffold _doujinshis_role name
rails g scaffold _doujinshis_staff_people name
rails g scaffold _doujinshis_role name
rails g scaffold _doujinshis_staff_people name
rails g scaffold _doujinshis_public_averti name
rails g scaffold _doujinshis_censure name
rails g scaffold _doujinshis_gratuit name
rails g scaffold _doujinshis_groupes name
rails g scaffold _doujinshis_anime name
rails g scaffold _doujinshis_anime_plus name
rails g scaffold _doujinshis_manga name
rails g scaffold _doujinshis_manga_plus name
rails g scaffold _doujinshis_ln name
rails g scaffold _doujinshis_ln_plus name
rails g scaffold _doujinshis_doujinshi name
rails g scaffold _doujinshis_doujinshi_plus name
rails g scaffold _doujinshis_drama name
rails g scaffold _doujinshis_drama_plus name
rails g scaffold _doujinshis_jv name
rails g scaffold _doujinshis_jv_plus name
rails g scaffold _doujinshis_am name
rails g scaffold _doujinshis_am_plus name
rails g scaffold _doujinshis_litterature_asiatique name
rails g scaffold _doujinshis_litterature_asiatique_plus name
rails g scaffold _doujinshis_artbook name
rails g scaffold _doujinshis_actualite name
rails g scaffold _doujinshis_culture name
rails g scaffold _doujinshis_actualite_mini name
rails g scaffold _doujinshis_perso name
rails g scaffold _doujinshis_perso_plus name
rails g scaffold _doujinshis_perso_manga name
rails g scaffold _doujinshis_jv_perso name
rails g scaffold _doujinshis_quizz name
rails g scaffold _doujinshis_people name
rails g scaffold _doujinshis _doujinshis_france_id:integer titre:string titre_alternatif:string titre_alternatif_suite:string titre_original_latin:string titre_original:string image:string image_vo:string _doujinshis_origine_id:integer _doujinshis_pays_id:integer _doujinshis_pays_id:integer _doujinshis_type_id:integer numerique:string _doujinshis_genres_id:integer _doujinshis_genres_id:integer _doujinshis_themes_id:integer _doujinshis_themes_id:integer _doujinshis_genres_averti_id:integer _doujinshis_genres_averti_id:integer date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string nb_page:string _doujinshis_conventions_id:integer _doujinshis_conventions_id:integer _doujinshis_role_id:integer _doujinshis_staff_people_id:integer _doujinshis_role_id:integer _doujinshis_staff_people_id:integer staff_txt:string _doujinshis_public_averti_id:integer _doujinshis_censure_id:integer tags:string prix:string _doujinshis_gratuit_id:integer lien_achat:string infos:text resume:text _doujinshis_groupes_id:integer _doujinshis_anime_id:integer _doujinshis_anime_plus_id:integer _doujinshis_manga_id:integer _doujinshis_manga_plus_id:integer _doujinshis_ln_id:integer _doujinshis_ln_plus_id:integer _doujinshis_doujinshi_id:integer _doujinshis_doujinshi_plus_id:integer _doujinshis_drama_id:integer _doujinshis_drama_plus_id:integer _doujinshis_jv_id:integer _doujinshis_jv_plus_id:integer _doujinshis_am_id:integer _doujinshis_am_plus_id:integer _doujinshis_litterature_asiatique_id:integer _doujinshis_litterature_asiatique_plus_id:integer _doujinshis_artbook_id:integer _doujinshis_actualite_id:integer _doujinshis_culture_id:integer _doujinshis_actualite_mini_id:integer _doujinshis_perso_id:integer _doujinshis_perso_plus_id:integer _doujinshis_perso_manga_id:integer _doujinshis_jv_perso_id:integer _doujinshis_quizz_id:integer _doujinshis_people_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _dramas_origine name
rails g scaffold _dramas_encours name
rails g scaffold _dramas_pays name
rails g scaffold _dramas_pays name
rails g scaffold _dramas_genres name
rails g scaffold _dramas_genres name
rails g scaffold _dramas_themes name
rails g scaffold _dramas_themes name
rails g scaffold _dramas_staff_role name
rails g scaffold _dramas_staff_people name
rails g scaffold _dramas_staff_role name
rails g scaffold _dramas_staff_people name
rails g scaffold _dramas_staff_role name
rails g scaffold _dramas_staff_people name
rails g scaffold _dramas_societe_role name
rails g scaffold _dramas_societe_people name
rails g scaffold _dramas_type name
rails g scaffold _dramas_acteurs name
rails g scaffold _dramas_type name
rails g scaffold _dramas_acteurs name
rails g scaffold _dramas_type name
rails g scaffold _dramas_acteurs name
rails g scaffold _dramas_type name
rails g scaffold _dramas_acteurs name
rails g scaffold _dramas_editeurs_vf_role name
rails g scaffold _dramas_editeurs_vf name
rails g scaffold _dramas_editeurs_vf_role name
rails g scaffold _dramas_editeurs_vf name
rails g scaffold _dramas_programme name
rails g scaffold _dramas_generiques_type name
rails g scaffold _dramas_generiques_people name
rails g scaffold _dramas_generiques_people2 name
rails g scaffold _dramas_generiques_clip name
rails g scaffold _dramas_generiques_parole name
rails g scaffold _dramas_generiques_type name
rails g scaffold _dramas_generiques_people name
rails g scaffold _dramas_generiques_people2 name
rails g scaffold _dramas_generiques_clip name
rails g scaffold _dramas_generiques_parole name
rails g scaffold _dramas_groupes name
rails g scaffold _dramas_anime name
rails g scaffold _dramas_anime_plus name
rails g scaffold _dramas_ln name
rails g scaffold _dramas_ln_plus name
rails g scaffold _dramas_manga name
rails g scaffold _dramas_manga_plus name
rails g scaffold _dramas_drama name
rails g scaffold _dramas_drama_plus name
rails g scaffold _dramas_jv name
rails g scaffold _dramas_jv_plus name
rails g scaffold _dramas_am name
rails g scaffold _dramas_am_plus name
rails g scaffold _dramas_univers name
rails g scaffold _dramas_litterature_asiatique name
rails g scaffold _dramas_litterature_asiatique_plus name
rails g scaffold _dramas_actualite name
rails g scaffold _dramas_culture name
rails g scaffold _dramas_actualite_mini name
rails g scaffold _dramas_ost name
rails g scaffold _dramas_doujin name
rails g scaffold _dramas_cd name
rails g scaffold _dramas_dvd name
rails g scaffold _dramas_artbook name
rails g scaffold _dramas_emission_tv name
rails g scaffold _dramas_emission_tv_plus name
rails g scaffold _dramas titre:string titre_alternatif:string titre_alternatif_suite:string titre_original_latin:string titre_original:string image:string _dramas_origine_id:integer _dramas_encours_id:integer date_debut_jj:string date_debut_mm:string date_debut_aaaa:string date_fin_jj:string date_fin_mm:string date_fin_aaaa:string nb_ep:string total_ep_inconnu:string _dramas_pays_id:integer _dramas_pays_id:integer duree:string age:string _dramas_genres_id:integer _dramas_genres_id:integer _dramas_themes_id:integer _dramas_themes_id:integer _dramas_staff_role_id:integer _dramas_staff_people_id:integer _dramas_staff_role_id:integer _dramas_staff_people_id:integer _dramas_staff_role_id:integer _dramas_staff_people_id:integer _dramas_societe_role_id:integer _dramas_societe_people_id:integer _dramas_type_id:integer _dramas_acteurs_id:integer _dramas_type_id:integer _dramas_acteurs_id:integer _dramas_type_id:integer _dramas_acteurs_id:integer _dramas_type_id:integer _dramas_acteurs_id:integer synopsis:text youtube:string webdrama:string webdrama:string _dramas_editeurs_vf_role_id:integer _dramas_editeurs_vf_id:integer _dramas_editeurs_vf_role_id:integer _dramas_editeurs_vf_id:integer date_debut_simulcast_jj:string date_debut_simulcast_mm:string date_debut_simulcast_aaaa:string licencie:string licencie:string date_vf_jj:string date_vf_mm:string date_vf_aaaa:string site:string site2:string _dramas_programme_id:integer episodes:text _dramas_generiques_type_id:integer _dramas_generiques_people_id:integer _dramas_generiques_people2_id:integer _dramas_generiques_clip_id:integer _dramas_generiques_parole_id:integer _dramas_generiques_type_id:integer _dramas_generiques_people_id:integer _dramas_generiques_people2_id:integer _dramas_generiques_clip_id:integer _dramas_generiques_parole_id:integer infos:text _dramas_groupes_id:integer _dramas_anime_id:integer _dramas_anime_plus_id:integer _dramas_ln_id:integer _dramas_ln_plus_id:integer _dramas_manga_id:integer _dramas_manga_plus_id:integer _dramas_drama_id:integer _dramas_drama_plus_id:integer _dramas_jv_id:integer _dramas_jv_plus_id:integer _dramas_am_id:integer _dramas_am_plus_id:integer _dramas_univers_id:integer _dramas_litterature_asiatique_id:integer _dramas_litterature_asiatique_plus_id:integer _dramas_actualite_id:integer _dramas_culture_id:integer _dramas_actualite_mini_id:integer _dramas_ost_id:integer _dramas_doujin_id:integer _dramas_cd_id:integer _dramas_dvd_id:integer _dramas_artbook_id:integer _dramas_emission_tv_id:integer _dramas_emission_tv_plus_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _fiche_univers_cat name
rails g scaffold _fiche_univers_groupes name
rails g scaffold _fiche_univers_univers name
rails g scaffold _fiche_univers_anime name
rails g scaffold _fiche_univers_perso name
rails g scaffold _fiche_univers_manga name
rails g scaffold _fiche_univers_perso_manga name
rails g scaffold _fiche_univers_ln name
rails g scaffold _fiche_univers_doujinshi name
rails g scaffold _fiche_univers_jv name
rails g scaffold _fiche_univers_jv_perso name
rails g scaffold _fiche_univers_drama name
rails g scaffold _fiche_univers_am name
rails g scaffold _fiche_univers_litterature_asiatique name
rails g scaffold _fiche_univers_people name
rails g scaffold _fiche_univers_actualite name
rails g scaffold _fiche_univers_actualite_mini name
rails g scaffold _fiche_univers_culture name
rails g scaffold _fiche_univers nom:string nom_alternatif:string nom_suite:string nom_original:string image:string _fiche_univers_cat_id:integer description:text _fiche_univers_groupes_id:integer _fiche_univers_univers_id:integer _fiche_univers_anime_id:integer _fiche_univers_perso_id:integer _fiche_univers_manga_id:integer _fiche_univers_perso_manga_id:integer _fiche_univers_ln_id:integer _fiche_univers_doujinshi_id:integer _fiche_univers_jv_id:integer _fiche_univers_jv_perso_id:integer _fiche_univers_drama_id:integer _fiche_univers_am_id:integer _fiche_univers_litterature_asiatique_id:integer _fiche_univers_people_id:integer _fiche_univers_actualite_id:integer _fiche_univers_actualite_mini_id:integer _fiche_univers_culture_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _films_asiatiques_en_salles_pays name
rails g scaffold _films_asiatiques_en_salles_langue name
rails g scaffold _films_asiatiques_en_salles_pays name
rails g scaffold _films_asiatiques_en_salles_langue name
rails g scaffold _films_asiatiques_en_salles_pays_origine name
rails g scaffold _films_asiatiques_en_salles_pays_origine name
rails g scaffold _films_asiatiques_en_salles_genres name
rails g scaffold _films_asiatiques_en_salles_genres name
rails g scaffold _films_asiatiques_en_salles_staff_role name
rails g scaffold _films_asiatiques_en_salles_staff_people name
rails g scaffold _films_asiatiques_en_salles_staff_role name
rails g scaffold _films_asiatiques_en_salles_staff_people name
rails g scaffold _films_asiatiques_en_salles_type name
rails g scaffold _films_asiatiques_en_salles_acteurs name
rails g scaffold _films_asiatiques_en_salles_type name
rails g scaffold _films_asiatiques_en_salles_acteurs name
rails g scaffold _films_asiatiques_en_salles_anime name
rails g scaffold _films_asiatiques_en_salles_am name
rails g scaffold _films_asiatiques_en_salles_drama name
rails g scaffold _films_asiatiques_en_salles_actualite name
rails g scaffold _films_asiatiques_en_salles_actualite_mini name
rails g scaffold _films_asiatiques_en_salles titre:string titre_original:string _films_asiatiques_en_salles_pays_id:integer :string _films_asiatiques_en_salles_langue_id:integer _films_asiatiques_en_salles_pays_id:integer :string _films_asiatiques_en_salles_langue_id:integer image:string annee:string _films_asiatiques_en_salles_pays_origine_id:integer _films_asiatiques_en_salles_pays_origine_id:integer duree:string age:string _films_asiatiques_en_salles_genres_id:integer _films_asiatiques_en_salles_genres_id:integer youtube:string site:string site2:string _films_asiatiques_en_salles_staff_role_id:integer _films_asiatiques_en_salles_staff_people_id:integer _films_asiatiques_en_salles_staff_role_id:integer _films_asiatiques_en_salles_staff_people_id:integer _films_asiatiques_en_salles_type_id:integer _films_asiatiques_en_salles_acteurs_id:integer _films_asiatiques_en_salles_type_id:integer _films_asiatiques_en_salles_acteurs_id:integer _films_asiatiques_en_salles_anime_id:integer _films_asiatiques_en_salles_am_id:integer _films_asiatiques_en_salles_drama_id:integer _films_asiatiques_en_salles_actualite_id:integer _films_asiatiques_en_salles_actualite_mini_id:integer synopsis:text recompense:text comment:text acceptregles:string
rails g scaffold _films_asiatiques_origine name
rails g scaffold _films_asiatiques_pays name
rails g scaffold _films_asiatiques_pays name
rails g scaffold _films_asiatiques_genres name
rails g scaffold _films_asiatiques_genres name
rails g scaffold _films_asiatiques_themes name
rails g scaffold _films_asiatiques_themes name
rails g scaffold _films_asiatiques_staff_role name
rails g scaffold _films_asiatiques_staff_people name
rails g scaffold _films_asiatiques_staff_role name
rails g scaffold _films_asiatiques_staff_people name
rails g scaffold _films_asiatiques_staff_role name
rails g scaffold _films_asiatiques_staff_people name
rails g scaffold _films_asiatiques_societe_role name
rails g scaffold _films_asiatiques_societe_people name
rails g scaffold _films_asiatiques_type name
rails g scaffold _films_asiatiques_acteurs name
rails g scaffold _films_asiatiques_type name
rails g scaffold _films_asiatiques_acteurs name
rails g scaffold _films_asiatiques_type name
rails g scaffold _films_asiatiques_acteurs name
rails g scaffold _films_asiatiques_type name
rails g scaffold _films_asiatiques_acteurs name
rails g scaffold _films_asiatiques_editeurs_vf_role name
rails g scaffold _films_asiatiques_editeurs_vf name
rails g scaffold _films_asiatiques_editeurs_vf_role name
rails g scaffold _films_asiatiques_editeurs_vf name
rails g scaffold _films_asiatiques_generiques_type name
rails g scaffold _films_asiatiques_generiques_people name
rails g scaffold _films_asiatiques_generiques_people2 name
rails g scaffold _films_asiatiques_generiques_clip name
rails g scaffold _films_asiatiques_generiques_parole name
rails g scaffold _films_asiatiques_generiques_type name
rails g scaffold _films_asiatiques_generiques_people name
rails g scaffold _films_asiatiques_generiques_people2 name
rails g scaffold _films_asiatiques_generiques_clip name
rails g scaffold _films_asiatiques_generiques_parole name
rails g scaffold _films_asiatiques_groupes name
rails g scaffold _films_asiatiques_anime name
rails g scaffold _films_asiatiques_anime_plus name
rails g scaffold _films_asiatiques_ln name
rails g scaffold _films_asiatiques_ln_plus name
rails g scaffold _films_asiatiques_manga name
rails g scaffold _films_asiatiques_manga_plus name
rails g scaffold _films_asiatiques_drama name
rails g scaffold _films_asiatiques_drama_plus name
rails g scaffold _films_asiatiques_jv name
rails g scaffold _films_asiatiques_jv_plus name
rails g scaffold _films_asiatiques_am name
rails g scaffold _films_asiatiques_am_plus name
rails g scaffold _films_asiatiques_cinema name
rails g scaffold _films_asiatiques_univers name
rails g scaffold _films_asiatiques_people name
rails g scaffold _films_asiatiques_litterature_asiatique name
rails g scaffold _films_asiatiques_litterature_asiatique_plus name
rails g scaffold _films_asiatiques_actualite name
rails g scaffold _films_asiatiques_culture name
rails g scaffold _films_asiatiques_emission_tv name
rails g scaffold _films_asiatiques_emission_tv_plus name
rails g scaffold _films_asiatiques_actualite_mini name
rails g scaffold _films_asiatiques_ost name
rails g scaffold _films_asiatiques_doujin name
rails g scaffold _films_asiatiques_cd name
rails g scaffold _films_asiatiques_sondage name
rails g scaffold _films_asiatiques_quizz name
rails g scaffold _films_asiatiques_concours name
rails g scaffold _films_asiatiques_dvd name
rails g scaffold _films_asiatiques_artbook name
rails g scaffold _films_asiatiques titre:string titre_alternatif:string titre_alternatif_suite:string titre_original_latin:string titre_original:string image:string image_internationale:string image_francaise:string _films_asiatiques_origine_id:integer date_debut_jj:string date_debut_mm:string date_debut_aaaa:string _films_asiatiques_pays_id:integer _films_asiatiques_pays_id:integer duree:string age:string _films_asiatiques_genres_id:integer _films_asiatiques_genres_id:integer _films_asiatiques_themes_id:integer _films_asiatiques_themes_id:integer _films_asiatiques_staff_role_id:integer _films_asiatiques_staff_people_id:integer _films_asiatiques_staff_role_id:integer _films_asiatiques_staff_people_id:integer _films_asiatiques_staff_role_id:integer _films_asiatiques_staff_people_id:integer _films_asiatiques_societe_role_id:integer _films_asiatiques_societe_people_id:integer _films_asiatiques_type_id:integer _films_asiatiques_acteurs_id:integer _films_asiatiques_type_id:integer _films_asiatiques_acteurs_id:integer _films_asiatiques_type_id:integer _films_asiatiques_acteurs_id:integer _films_asiatiques_type_id:integer _films_asiatiques_acteurs_id:integer synopsis:text youtube:string licencie:string licencie:string date_vf_jj:string date_vf_mm:string date_vf_aaaa:string _films_asiatiques_editeurs_vf_role_id:integer _films_asiatiques_editeurs_vf_id:integer _films_asiatiques_editeurs_vf_role_id:integer _films_asiatiques_editeurs_vf_id:integer date_debut_simulcast_jj:string date_debut_simulcast_mm:string date_debut_simulcast_aaaa:string site:string _films_asiatiques_generiques_type_id:integer _films_asiatiques_generiques_people_id:integer _films_asiatiques_generiques_people2_id:integer _films_asiatiques_generiques_clip_id:integer _films_asiatiques_generiques_parole_id:integer _films_asiatiques_generiques_type_id:integer _films_asiatiques_generiques_people_id:integer _films_asiatiques_generiques_people2_id:integer _films_asiatiques_generiques_clip_id:integer _films_asiatiques_generiques_parole_id:integer infos:text _films_asiatiques_groupes_id:integer _films_asiatiques_anime_id:integer _films_asiatiques_anime_plus_id:integer _films_asiatiques_ln_id:integer _films_asiatiques_ln_plus_id:integer _films_asiatiques_manga_id:integer _films_asiatiques_manga_plus_id:integer _films_asiatiques_drama_id:integer _films_asiatiques_drama_plus_id:integer _films_asiatiques_jv_id:integer _films_asiatiques_jv_plus_id:integer _films_asiatiques_am_id:integer _films_asiatiques_am_plus_id:integer _films_asiatiques_cinema_id:integer _films_asiatiques_univers_id:integer _films_asiatiques_people_id:integer _films_asiatiques_litterature_asiatique_id:integer _films_asiatiques_litterature_asiatique_plus_id:integer _films_asiatiques_actualite_id:integer _films_asiatiques_culture_id:integer _films_asiatiques_emission_tv_id:integer _films_asiatiques_emission_tv_plus_id:integer _films_asiatiques_actualite_mini_id:integer _films_asiatiques_ost_id:integer _films_asiatiques_doujin_id:integer _films_asiatiques_cd_id:integer _films_asiatiques_sondage_id:integer _films_asiatiques_quizz_id:integer _films_asiatiques_concours_id:integer _films_asiatiques_dvd_id:integer _films_asiatiques_artbook_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _generique_de_jeu_videos_type name
rails g scaffold _generique_de_jeu_videos_staff_role name
rails g scaffold _generique_de_jeu_videos_staff_people name
rails g scaffold _generique_de_jeu_videos_staff_role name
rails g scaffold _generique_de_jeu_videos_staff_people name
rails g scaffold _generique_de_jeu_videos_jv name
rails g scaffold _generique_de_jeu_videos_jv_generic name
rails g scaffold _generique_de_jeu_videos titre:string titre_original:string _generique_de_jeu_videos_type_id:integer number:string _generique_de_jeu_videos_staff_role_id:integer _generique_de_jeu_videos_staff_people_id:integer _generique_de_jeu_videos_staff_role_id:integer _generique_de_jeu_videos_staff_people_id:integer description:text instrumental:string instrumental:string date_jj:string date_mm:string date_aaaa:string youtube:string paroles:text paroles_trad:text membre_show:string membre_show:string _generique_de_jeu_videos_jv_id:integer _generique_de_jeu_videos_jv_generic_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _generiques_id_anime name
rails g scaffold _generiques_type name
rails g scaffold _generiques_staff_role name
rails g scaffold _generiques_staff_people name
rails g scaffold _generiques_staff_role name
rails g scaffold _generiques_staff_people name
rails g scaffold _generiques_generic name
rails g scaffold _generiques titre:string titre_original:string _generiques_id_anime_id:integer _generiques_type_id:integer number:string _generiques_staff_role_id:integer _generiques_staff_people_id:integer _generiques_staff_role_id:integer _generiques_staff_people_id:integer description:text instrumental:string instrumental:string date_jj:string date_mm:string date_aaaa:string youtube:string paroles:text paroles_trad:text membre_show:string membre_show:string episodes:string _generiques_generic_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _jeux_videos_plateforme name
rails g scaffold _jeux_videos_pays_date name
rails g scaffold _jeux_videos_pays name
rails g scaffold _jeux_videos_pays name
rails g scaffold _jeux_videos_etat name
rails g scaffold _jeux_videos_themes name
rails g scaffold _jeux_videos_themes name
rails g scaffold _jeux_videos_genres name
rails g scaffold _jeux_videos_genres name
rails g scaffold _jeux_videos_staff_societe_role name
rails g scaffold _jeux_videos_staff_societe name
rails g scaffold _jeux_videos_staff_societe_role name
rails g scaffold _jeux_videos_staff_societe name
rails g scaffold _jeux_videos_staff_role name
rails g scaffold _jeux_videos_staff_people name
rails g scaffold _jeux_videos_groupes name
rails g scaffold _jeux_videos_actualite name
rails g scaffold _jeux_videos_actualite_mini name
rails g scaffold _jeux_videos_anime name
rails g scaffold _jeux_videos_anime_plus name
rails g scaffold _jeux_videos_ln name
rails g scaffold _jeux_videos_ln_plus name
rails g scaffold _jeux_videos_manga name
rails g scaffold _jeux_videos_manga_plus name
rails g scaffold _jeux_videos_jv name
rails g scaffold _jeux_videos_jv_plus name
rails g scaffold _jeux_videos_am name
rails g scaffold _jeux_videos_am_plus name
rails g scaffold _jeux_videos_drama name
rails g scaffold _jeux_videos_drama_plus name
rails g scaffold _jeux_videos_univers name
rails g scaffold _jeux_videos_dvd name
rails g scaffold _jeux_videos_artbook name
rails g scaffold _jeux_videos_litterature_asiatique name
rails g scaffold _jeux_videos_litterature_asiatique_plus name
rails g scaffold _jeux_videos_culture name
rails g scaffold _jeux_videos_ost name
rails g scaffold _jeux_videos_cd name
rails g scaffold _jeux_videos_doujin name
rails g scaffold _jeux_videos_amv name
rails g scaffold _jeux_videos_sondage name
rails g scaffold _jeux_videos_quizz name
rails g scaffold _jeux_videos_concours name
rails g scaffold _jeux_videos_people name
rails g scaffold _jeux_videos_topic name
rails g scaffold _jeux_videos titre_fr:string titre_original_latin:string titre_us:string titre_alternatif:string titre_original:string _jeux_videos_plateforme_id:integer date_fr_jj:string date_fr_mm:string date_fr_aaaa:string _jeux_videos_pays_date_id:integer date_originale_jj:string date_originale_mm:string date_originale_aaaa:string date_us_jj:string date_us_mm:string date_us_aaaa:string date_jap_jj:string date_jap_mm:string date_jap_aaaa:string _jeux_videos_pays_id:integer _jeux_videos_pays_id:integer _jeux_videos_etat_id:integer prix:string ean:string _jeux_videos_themes_id:integer _jeux_videos_themes_id:integer _jeux_videos_genres_id:integer _jeux_videos_genres_id:integer multi:string multi:string multi_nb:string online:string online:string age:string site:string pochette_eu:string pochette_asie:string pochette_us:string _jeux_videos_staff_societe_role_id:integer _jeux_videos_staff_societe_id:integer _jeux_videos_staff_societe_role_id:integer _jeux_videos_staff_societe_id:integer _jeux_videos_staff_role_id:integer _jeux_videos_staff_people_id:integer description:text youtube:string _jeux_videos_groupes_id:integer _jeux_videos_actualite_id:integer _jeux_videos_actualite_mini_id:integer _jeux_videos_anime_id:integer _jeux_videos_anime_plus_id:integer _jeux_videos_ln_id:integer _jeux_videos_ln_plus_id:integer _jeux_videos_manga_id:integer _jeux_videos_manga_plus_id:integer _jeux_videos_jv_id:integer _jeux_videos_jv_plus_id:integer _jeux_videos_am_id:integer _jeux_videos_am_plus_id:integer _jeux_videos_drama_id:integer _jeux_videos_drama_plus_id:integer _jeux_videos_univers_id:integer _jeux_videos_dvd_id:integer _jeux_videos_artbook_id:integer _jeux_videos_litterature_asiatique_id:integer _jeux_videos_litterature_asiatique_plus_id:integer _jeux_videos_culture_id:integer _jeux_videos_ost_id:integer _jeux_videos_cd_id:integer _jeux_videos_doujin_id:integer _jeux_videos_amv_id:integer _jeux_videos_sondage_id:integer _jeux_videos_quizz_id:integer _jeux_videos_concours_id:integer _jeux_videos_people_id:integer _jeux_videos_topic_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _light_novels_pays name
rails g scaffold _light_novels_pays name
rails g scaffold _light_novels_genres name
rails g scaffold _light_novels_genres name
rails g scaffold _light_novels_themes name
rails g scaffold _light_novels_themes name
rails g scaffold _light_novels_encours_vo name
rails g scaffold _light_novels_encours_vf name
rails g scaffold _light_novels_editeurs_vo name
rails g scaffold _light_novels_editeurs_vo name
rails g scaffold _light_novels_editeurs_vf name
rails g scaffold _light_novels_editeurs_vf_collection name
rails g scaffold _light_novels_editeurs_vf name
rails g scaffold _light_novels_editeurs_vf_collection name
rails g scaffold _light_novels_prepublie name
rails g scaffold _light_novels_prepublie name
rails g scaffold _light_novels_staff_role name
rails g scaffold _light_novels_staff_people name
rails g scaffold _light_novels_staff_role name
rails g scaffold _light_novels_staff_people name
rails g scaffold _light_novels_societe_role name
rails g scaffold _light_novels_societe_people name
rails g scaffold _light_novels_societe_role name
rails g scaffold _light_novels_societe_people name
rails g scaffold _light_novels_public_averti name
rails g scaffold _light_novels_commerce name
rails g scaffold _light_novels_groupes name
rails g scaffold _light_novels_anime name
rails g scaffold _light_novels_anime_plus name
rails g scaffold _light_novels_manga name
rails g scaffold _light_novels_manga_plus name
rails g scaffold _light_novels_ln name
rails g scaffold _light_novels_ln_plus name
rails g scaffold _light_novels_drama name
rails g scaffold _light_novels_drama_plus name
rails g scaffold _light_novels_jv name
rails g scaffold _light_novels_jv_plus name
rails g scaffold _light_novels_am name
rails g scaffold _light_novels_am_plus name
rails g scaffold _light_novels_litterature_asiatique name
rails g scaffold _light_novels_litterature_asiatique_plus name
rails g scaffold _light_novels_ost name
rails g scaffold _light_novels_artbook name
rails g scaffold _light_novels_actualite name
rails g scaffold _light_novels_culture name
rails g scaffold _light_novels_actualite_mini name
rails g scaffold _light_novels_quizz name
rails g scaffold _light_novels titre:string titre_alternatif:string titre_alternatif_suite:string titre_original_latin:string titre_original:string image:string image_vo:string _light_novels_pays_id:integer _light_novels_pays_id:integer _light_novels_genres_id:integer _light_novels_genres_id:integer webcomic:string _light_novels_themes_id:integer _light_novels_themes_id:integer annee_vo:string annee_vf:string nb_volumes_vo:string nb_chapitres_vo:string nb_volumes_vf:string nb_chapitres_vf:string _light_novels_encours_vo_id:integer _light_novels_encours_vf_id:integer _light_novels_editeurs_vo_id:integer _light_novels_editeurs_vo_id:integer _light_novels_editeurs_vf_id:integer _light_novels_editeurs_vf_collection_id:integer _light_novels_editeurs_vf_id:integer _light_novels_editeurs_vf_collection_id:integer _light_novels_prepublie_id:integer _light_novels_prepublie_id:integer _light_novels_staff_role_id:integer _light_novels_staff_people_id:integer _light_novels_staff_role_id:integer _light_novels_staff_people_id:integer _light_novels_societe_role_id:integer _light_novels_societe_people_id:integer _light_novels_societe_role_id:integer _light_novels_societe_people_id:integer age:string _light_novels_public_averti_id:integer _light_novels_commerce_id:integer adapte_anime:string adapte_anime:string adapte_anime:string prix:string resume:text _light_novels_groupes_id:integer _light_novels_anime_id:integer _light_novels_anime_plus_id:integer _light_novels_manga_id:integer _light_novels_manga_plus_id:integer _light_novels_ln_id:integer _light_novels_ln_plus_id:integer _light_novels_drama_id:integer _light_novels_drama_plus_id:integer _light_novels_jv_id:integer _light_novels_jv_plus_id:integer _light_novels_am_id:integer _light_novels_am_plus_id:integer _light_novels_litterature_asiatique_id:integer _light_novels_litterature_asiatique_plus_id:integer _light_novels_ost_id:integer _light_novels_artbook_id:integer _light_novels_actualite_id:integer _light_novels_culture_id:integer _light_novels_actualite_mini_id:integer _light_novels_quizz_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _livres_type name
rails g scaffold _livres_type_secondaire name
rails g scaffold _livres_pays name
rails g scaffold _livres_statut_publication name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_genres name
rails g scaffold _livres_genres name
rails g scaffold _livres_themes name
rails g scaffold _livres_themes name
rails g scaffold _livres_pays_theme name
rails g scaffold _livres_public_averti name
rails g scaffold _livres_groupes name
rails g scaffold _livres_anime name
rails g scaffold _livres_anime_plus name
rails g scaffold _livres_ln name
rails g scaffold _livres_ln_plus name
rails g scaffold _livres_manga name
rails g scaffold _livres_manga_plus name
rails g scaffold _livres_drama name
rails g scaffold _livres_drama_plus name
rails g scaffold _livres_am name
rails g scaffold _livres_am_plus name
rails g scaffold _livres_litterature_asiatique name
rails g scaffold _livres_litterature_asiatique_plus name
rails g scaffold _livres_goodies name
rails g scaffold _livres_actualite name
rails g scaffold _livres_culture name
rails g scaffold _livres_actualite_mini name
rails g scaffold _livres_people name
rails g scaffold _livres_jv name
rails g scaffold _livres_jv_plus name
rails g scaffold _livres _livres_type_id:integer _livres_type_secondaire_id:integer titre:string titre_original_latin:string titre_original:string image:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string _livres_pays_id:integer ean:string pages:string prix:string gratuit:string age:string _livres_statut_publication_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vf_id:integer _livres_editeurs_vf_id:integer collection:string traducteur:string _livres_genres_id:integer _livres_genres_id:integer _livres_themes_id:integer _livres_themes_id:integer _livres_pays_theme_id:integer _livres_public_averti_id:integer resume:text preview:string _livres_groupes_id:integer _livres_anime_id:integer _livres_anime_plus_id:integer _livres_ln_id:integer _livres_ln_plus_id:integer _livres_manga_id:integer _livres_manga_plus_id:integer _livres_drama_id:integer _livres_drama_plus_id:integer _livres_am_id:integer _livres_am_plus_id:integer _livres_litterature_asiatique_id:integer _livres_litterature_asiatique_plus_id:integer _livres_goodies_id:integer _livres_actualite_id:integer _livres_culture_id:integer _livres_actualite_mini_id:integer _livres_people_id:integer _livres_jv_id:integer _livres_jv_plus_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _livres_type name
rails g scaffold _livres_pays name
rails g scaffold _livres_statut_publication name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_genres name
rails g scaffold _livres_genres name
rails g scaffold _livres_themes name
rails g scaffold _livres_themes name
rails g scaffold _livres_pays_theme name
rails g scaffold _livres_public_averti name
rails g scaffold _livres_groupes name
rails g scaffold _livres_anime name
rails g scaffold _livres_anime_plus name
rails g scaffold _livres_ln name
rails g scaffold _livres_ln_plus name
rails g scaffold _livres_manga name
rails g scaffold _livres_manga_plus name
rails g scaffold _livres_drama name
rails g scaffold _livres_drama_plus name
rails g scaffold _livres_am name
rails g scaffold _livres_am_plus name
rails g scaffold _livres_litterature_asiatique name
rails g scaffold _livres_litterature_asiatique_plus name
rails g scaffold _livres_goodies name
rails g scaffold _livres_actualite name
rails g scaffold _livres_culture name
rails g scaffold _livres_actualite_mini name
rails g scaffold _livres_people name
rails g scaffold _livres_jv name
rails g scaffold _livres_jv_plus name
rails g scaffold _livres _livres_type_id:integer titre:string titre_original_latin:string titre_original:string image:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string _livres_pays_id:integer ean:string pages:string prix:string gratuit:string age:string _livres_statut_publication_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vf_id:integer _livres_editeurs_vf_id:integer collection:string traducteur:string _livres_genres_id:integer _livres_genres_id:integer _livres_themes_id:integer _livres_themes_id:integer _livres_pays_theme_id:integer _livres_public_averti_id:integer resume:text preview:string _livres_groupes_id:integer _livres_anime_id:integer _livres_anime_plus_id:integer _livres_ln_id:integer _livres_ln_plus_id:integer _livres_manga_id:integer _livres_manga_plus_id:integer _livres_drama_id:integer _livres_drama_plus_id:integer _livres_am_id:integer _livres_am_plus_id:integer _livres_litterature_asiatique_id:integer _livres_litterature_asiatique_plus_id:integer _livres_goodies_id:integer _livres_actualite_id:integer _livres_culture_id:integer _livres_actualite_mini_id:integer _livres_people_id:integer _livres_jv_id:integer _livres_jv_plus_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _livres_type name
rails g scaffold _livres_pays name
rails g scaffold _livres_statut_publication name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_genres name
rails g scaffold _livres_genres name
rails g scaffold _livres_themes name
rails g scaffold _livres_themes name
rails g scaffold _livres_pays_theme name
rails g scaffold _livres_public_averti name
rails g scaffold _livres_groupes name
rails g scaffold _livres_anime name
rails g scaffold _livres_anime_plus name
rails g scaffold _livres_ln name
rails g scaffold _livres_ln_plus name
rails g scaffold _livres_manga name
rails g scaffold _livres_manga_plus name
rails g scaffold _livres_drama name
rails g scaffold _livres_drama_plus name
rails g scaffold _livres_am name
rails g scaffold _livres_am_plus name
rails g scaffold _livres_litterature_asiatique name
rails g scaffold _livres_litterature_asiatique_plus name
rails g scaffold _livres_goodies name
rails g scaffold _livres_actualite name
rails g scaffold _livres_culture name
rails g scaffold _livres_actualite_mini name
rails g scaffold _livres_people name
rails g scaffold _livres_jv name
rails g scaffold _livres_jv_plus name
rails g scaffold _livres _livres_type_id:integer titre:string titre_original_latin:string titre_original:string image:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string _livres_pays_id:integer ean:string pages:string prix:string gratuit:string age:string _livres_statut_publication_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vf_id:integer _livres_editeurs_vf_id:integer collection:string traducteur:string _livres_genres_id:integer _livres_genres_id:integer _livres_themes_id:integer _livres_themes_id:integer _livres_pays_theme_id:integer _livres_public_averti_id:integer resume:text preview:string _livres_groupes_id:integer _livres_anime_id:integer _livres_anime_plus_id:integer _livres_ln_id:integer _livres_ln_plus_id:integer _livres_manga_id:integer _livres_manga_plus_id:integer _livres_drama_id:integer _livres_drama_plus_id:integer _livres_am_id:integer _livres_am_plus_id:integer _livres_litterature_asiatique_id:integer _livres_litterature_asiatique_plus_id:integer _livres_goodies_id:integer _livres_actualite_id:integer _livres_culture_id:integer _livres_actualite_mini_id:integer _livres_people_id:integer _livres_jv_id:integer _livres_jv_plus_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _livres_type name
rails g scaffold _livres_type_secondaire name
rails g scaffold _livres_pays name
rails g scaffold _livres_statut_publication name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_staff_role name
rails g scaffold _livres_staff_people name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vo name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_editeurs_vf name
rails g scaffold _livres_genres name
rails g scaffold _livres_genres name
rails g scaffold _livres_themes name
rails g scaffold _livres_themes name
rails g scaffold _livres_pays_theme name
rails g scaffold _livres_public_averti name
rails g scaffold _livres_groupes name
rails g scaffold _livres_anime name
rails g scaffold _livres_anime_plus name
rails g scaffold _livres_ln name
rails g scaffold _livres_ln_plus name
rails g scaffold _livres_manga name
rails g scaffold _livres_manga_plus name
rails g scaffold _livres_drama name
rails g scaffold _livres_drama_plus name
rails g scaffold _livres_am name
rails g scaffold _livres_am_plus name
rails g scaffold _livres_litterature_asiatique name
rails g scaffold _livres_litterature_asiatique_plus name
rails g scaffold _livres_goodies name
rails g scaffold _livres_actualite name
rails g scaffold _livres_culture name
rails g scaffold _livres_actualite_mini name
rails g scaffold _livres_people name
rails g scaffold _livres_jv name
rails g scaffold _livres_jv_plus name
rails g scaffold _livres _livres_type_id:integer _livres_type_secondaire_id:integer titre:string titre_original_latin:string titre_original:string image:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string _livres_pays_id:integer ean:string pages:string prix:string gratuit:string age:string _livres_statut_publication_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_staff_role_id:integer _livres_staff_people_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vo_id:integer _livres_editeurs_vf_id:integer _livres_editeurs_vf_id:integer collection:string traducteur:string _livres_genres_id:integer _livres_genres_id:integer _livres_themes_id:integer _livres_themes_id:integer _livres_pays_theme_id:integer _livres_public_averti_id:integer resume:text preview:string _livres_groupes_id:integer _livres_anime_id:integer _livres_anime_plus_id:integer _livres_ln_id:integer _livres_ln_plus_id:integer _livres_manga_id:integer _livres_manga_plus_id:integer _livres_drama_id:integer _livres_drama_plus_id:integer _livres_am_id:integer _livres_am_plus_id:integer _livres_litterature_asiatique_id:integer _livres_litterature_asiatique_plus_id:integer _livres_goodies_id:integer _livres_actualite_id:integer _livres_culture_id:integer _livres_actualite_mini_id:integer _livres_people_id:integer _livres_jv_id:integer _livres_jv_plus_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _mangas_pays name
rails g scaffold _mangas_pays name
rails g scaffold _mangas_type name
rails g scaffold _mangas_genres name
rails g scaffold _mangas_genres name
rails g scaffold _mangas_themes name
rails g scaffold _mangas_themes name
rails g scaffold _mangas_encours_vo name
rails g scaffold _mangas_encours_vf name
rails g scaffold _mangas_editeurs_vo name
rails g scaffold _mangas_editeurs_vo name
rails g scaffold _mangas_editeurs_vf name
rails g scaffold _mangas_editeurs_vf_collection name
rails g scaffold _mangas_editeurs_vf name
rails g scaffold _mangas_editeurs_vf_collection name
rails g scaffold _mangas_prepublie name
rails g scaffold _mangas_prepublie name
rails g scaffold _mangas_staff_role name
rails g scaffold _mangas_staff_people name
rails g scaffold _mangas_staff_role name
rails g scaffold _mangas_staff_people name
rails g scaffold _mangas_societe_role name
rails g scaffold _mangas_societe_people name
rails g scaffold _mangas_societe_role name
rails g scaffold _mangas_societe_people name
rails g scaffold _mangas_public_averti name
rails g scaffold _mangas_commerce name
rails g scaffold _mangas_groupes name
rails g scaffold _mangas_anime name
rails g scaffold _mangas_anime_plus name
rails g scaffold _mangas_ln name
rails g scaffold _mangas_ln_plus name
rails g scaffold _mangas_manga name
rails g scaffold _mangas_manga_plus name
rails g scaffold _mangas_drama name
rails g scaffold _mangas_drama_plus name
rails g scaffold _mangas_jv name
rails g scaffold _mangas_jv_plus name
rails g scaffold _mangas_am name
rails g scaffold _mangas_am_plus name
rails g scaffold _mangas_litterature_asiatique name
rails g scaffold _mangas_litterature_asiatique_plus name
rails g scaffold _mangas_artbook name
rails g scaffold _mangas_actualite name
rails g scaffold _mangas_culture name
rails g scaffold _mangas_actualite_mini name
rails g scaffold _mangas_sondage name
rails g scaffold _mangas_quizz name
rails g scaffold _mangas_concours name
rails g scaffold _mangas_people name
rails g scaffold _mangas_clip name
rails g scaffold _mangas titre:string titre_alternatif:string titre_alternatif_suite:string titre_original_latin:string titre_original:string image:string image_vo:string _mangas_pays_id:integer _mangas_pays_id:integer _mangas_type_id:integer webcomic:string _mangas_genres_id:integer _mangas_genres_id:integer _mangas_themes_id:integer _mangas_themes_id:integer annee_vo:string annee_vf:string annee_defaut:string nb_volumes_vo:string nb_chapitres_vo:string nb_volumes_vf:string nb_chapitres_vf:string _mangas_encours_vo_id:integer _mangas_encours_vf_id:integer _mangas_editeurs_vo_id:integer _mangas_editeurs_vo_id:integer _mangas_editeurs_vf_id:integer _mangas_editeurs_vf_collection_id:integer _mangas_editeurs_vf_id:integer _mangas_editeurs_vf_collection_id:integer _mangas_prepublie_id:integer _mangas_prepublie_id:integer _mangas_staff_role_id:integer _mangas_staff_people_id:integer _mangas_staff_role_id:integer _mangas_staff_people_id:integer _mangas_societe_role_id:integer _mangas_societe_people_id:integer _mangas_societe_role_id:integer _mangas_societe_people_id:integer age:string _mangas_public_averti_id:integer _mangas_commerce_id:integer adapte_anime:string adapte_anime:string adapte_anime:string prix:string resume:text infos:text youtube:string _mangas_groupes_id:integer _mangas_anime_id:integer _mangas_anime_plus_id:integer _mangas_ln_id:integer _mangas_ln_plus_id:integer _mangas_manga_id:integer _mangas_manga_plus_id:integer _mangas_drama_id:integer _mangas_drama_plus_id:integer _mangas_jv_id:integer _mangas_jv_plus_id:integer _mangas_am_id:integer _mangas_am_plus_id:integer _mangas_litterature_asiatique_id:integer _mangas_litterature_asiatique_plus_id:integer _mangas_artbook_id:integer _mangas_actualite_id:integer _mangas_culture_id:integer _mangas_actualite_mini_id:integer _mangas_sondage_id:integer _mangas_quizz_id:integer _mangas_concours_id:integer _mangas_people_id:integer _mangas_clip_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _numero_demission_tvs_id_emission_tv name
rails g scaffold _numero_demission_tvs_special name
rails g scaffold _numero_demission_tvs_presentateur name
rails g scaffold _numero_demission_tvs_presentateur name
rails g scaffold _numero_demission_tvs_people name
rails g scaffold _numero_demission_tvs_people name
rails g scaffold _numero_demission_tvs_emission_tv_numero name
rails g scaffold _numero_demission_tvs_clip name
rails g scaffold _numero_demission_tvs _numero_demission_tvs_id_emission_tv_id:integer titre:string titre_original:string date_jj:string date_mm:string date_aaaa:string _numero_demission_tvs_special_id:integer duree:string _numero_demission_tvs_presentateur_id:integer _numero_demission_tvs_presentateur_id:integer _numero_demission_tvs_people_id:integer _numero_demission_tvs_people_id:integer image:string infos:text youtube:string _numero_demission_tvs_emission_tv_numero_id:integer _numero_demission_tvs_clip_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _paroles_staff_role name
rails g scaffold _paroles_staff_people name
rails g scaffold _paroles_staff_role name
rails g scaffold _paroles_staff_people name
rails g scaffold _paroles_parole name
rails g scaffold _paroles titre:string titre_original:string titre_alternatif:string titre_original_latin:string _paroles_staff_role_id:integer _paroles_staff_people_id:integer _paroles_staff_role_id:integer _paroles_staff_people_id:integer paroles:text paroles_trad:text membre_show:string membre_show:string source:string description:text instrumental:string instrumental:string _paroles_parole_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _personnage_danimes_sexe name
rails g scaffold _personnage_danimes_anime name
rails g scaffold _personnage_danimes_anime name
rails g scaffold _personnage_danimes_doubleur_pays name
rails g scaffold _personnage_danimes_doubleur_people name
rails g scaffold _personnage_danimes_doubleur_role name
rails g scaffold _personnage_danimes_doubleur_pays name
rails g scaffold _personnage_danimes_doubleur_people name
rails g scaffold _personnage_danimes_doubleur_role name
rails g scaffold _personnage_danimes_perso name
rails g scaffold _personnage_danimes_perso_plus name
rails g scaffold _personnage_danimes_perso_manga name
rails g scaffold _personnage_danimes_jv_perso name
rails g scaffold _personnage_danimes_goodies name
rails g scaffold _personnage_danimes nom:string nom_alternatif:string nom_suite:string nom_original:string _personnage_danimes_sexe_id:integer _personnage_danimes_anime_id:integer _personnage_danimes_anime_id:integer _personnage_danimes_doubleur_pays_id:integer _personnage_danimes_doubleur_people_id:integer :string _personnage_danimes_doubleur_role_id:integer _personnage_danimes_doubleur_pays_id:integer _personnage_danimes_doubleur_people_id:integer :string _personnage_danimes_doubleur_role_id:integer special:string special:string image:string description:text _personnage_danimes_perso_id:integer _personnage_danimes_perso_plus_id:integer _personnage_danimes_perso_manga_id:integer _personnage_danimes_jv_perso_id:integer _personnage_danimes_goodies_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _personnages_de_jeux_videos_jv name
rails g scaffold _personnages_de_jeux_videos_jv name
rails g scaffold _personnages_de_jeux_videos_doubleur_pays name
rails g scaffold _personnages_de_jeux_videos_doubleur_people name
rails g scaffold _personnages_de_jeux_videos_doubleur_role name
rails g scaffold _personnages_de_jeux_videos_doubleur_pays name
rails g scaffold _personnages_de_jeux_videos_doubleur_people name
rails g scaffold _personnages_de_jeux_videos_doubleur_role name
rails g scaffold _personnages_de_jeux_videos_jv_perso name
rails g scaffold _personnages_de_jeux_videos_perso name
rails g scaffold _personnages_de_jeux_videos_perso_plus name
rails g scaffold _personnages_de_jeux_videos_perso_manga name
rails g scaffold _personnages_de_jeux_videos_goodies name
rails g scaffold _personnages_de_jeux_videos nom:string nom_alternatif:string nom_suite:string nom_original:string _personnages_de_jeux_videos_jv_id:integer _personnages_de_jeux_videos_jv_id:integer jouable:string jouable:string muet:string _personnages_de_jeux_videos_doubleur_pays_id:integer _personnages_de_jeux_videos_doubleur_people_id:integer :string _personnages_de_jeux_videos_doubleur_role_id:integer _personnages_de_jeux_videos_doubleur_pays_id:integer _personnages_de_jeux_videos_doubleur_people_id:integer :string _personnages_de_jeux_videos_doubleur_role_id:integer _personnages_de_jeux_videos_jv_perso_id:integer _personnages_de_jeux_videos_perso_id:integer _personnages_de_jeux_videos_perso_plus_id:integer _personnages_de_jeux_videos_perso_manga_id:integer _personnages_de_jeux_videos_goodies_id:integer image:string description:text comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _personnage_de_mangas_manga name
rails g scaffold _personnage_de_mangas_manga name
rails g scaffold _personnage_de_mangas_perso_manga name
rails g scaffold _personnage_de_mangas_perso name
rails g scaffold _personnage_de_mangas_perso_plus name
rails g scaffold _personnage_de_mangas_jv_perso name
rails g scaffold _personnage_de_mangas_goodies name
rails g scaffold _personnage_de_mangas nom:string nom_alternatif:string nom_suite:string nom_original:string _personnage_de_mangas_manga_id:integer _personnage_de_mangas_manga_id:integer image:string description:text _personnage_de_mangas_perso_manga_id:integer _personnage_de_mangas_perso_id:integer _personnage_de_mangas_perso_plus_id:integer _personnage_de_mangas_jv_perso_id:integer _personnage_de_mangas_goodies_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _personnalites_type_people name
rails g scaffold _personnalites_sexe name
rails g scaffold _personnalites_pays name
rails g scaffold _personnalites_pays name
rails g scaffold _personnalites_statut name
rails g scaffold _personnalites_genres name
rails g scaffold _personnalites_genres name
rails g scaffold _personnalites_labels name
rails g scaffold _personnalites_labels_debut name
rails g scaffold _personnalites_labels_fin name
rails g scaffold _personnalites_labels_ex name
rails g scaffold _personnalites_labels name
rails g scaffold _personnalites_labels_debut name
rails g scaffold _personnalites_labels_fin name
rails g scaffold _personnalites_labels_ex name
rails g scaffold _personnalites_agences name
rails g scaffold _personnalites_agences_debut name
rails g scaffold _personnalites_agences_fin name
rails g scaffold _personnalites_agences_ex name
rails g scaffold _personnalites_agences name
rails g scaffold _personnalites_agences_debut name
rails g scaffold _personnalites_agences_fin name
rails g scaffold _personnalites_agences_ex name
rails g scaffold _personnalites_roles name
rails g scaffold _personnalites_roles name
rails g scaffold _personnalites_id_membre name
rails g scaffold _personnalites_ex name
rails g scaffold _personnalites_ex_debut name
rails g scaffold _personnalites_ex_fin name
rails g scaffold _personnalites_id_galerie name
rails g scaffold _personnalites_id_travaux name
rails g scaffold _personnalites_people name
rails g scaffold _personnalites_people_plus name
rails g scaffold _personnalites nom:string nom_alternatif:string nom_alternatif_suite:string nom_original_latin:string nom_original:string nom_original_2:string nom_original_3:string nom_original_4:string _personnalites_type_people_id:integer _personnalites_sexe_id:integer _personnalites_pays_id:integer _personnalites_pays_id:integer decede:string date_nais_jj:string date_nais_mm:string date_nais_aaaa:string date_deces_jj:string date_deces_mm:string date_deces_aaaa:string image:string _personnalites_statut_id:integer debut:string fin:string _personnalites_genres_id:integer _personnalites_genres_id:integer _personnalites_labels_id:integer _personnalites_labels_debut_id:integer _personnalites_labels_fin_id:integer _personnalites_labels_ex_id:integer _personnalites_labels_id:integer _personnalites_labels_debut_id:integer _personnalites_labels_fin_id:integer _personnalites_labels_ex_id:integer _personnalites_agences_id:integer _personnalites_agences_debut_id:integer _personnalites_agences_fin_id:integer _personnalites_agences_ex_id:integer _personnalites_agences_id:integer _personnalites_agences_debut_id:integer _personnalites_agences_fin_id:integer _personnalites_agences_ex_id:integer _personnalites_roles_id:integer _personnalites_roles_id:integer _personnalites_id_membre_id:integer _personnalites_ex_id:integer _personnalites_ex_debut_id:integer _personnalites_ex_fin_id:integer bio:text _personnalites_id_galerie_id:integer liaison_auto_galerie:string _personnalites_id_travaux_id:integer liaison_auto_cosplay:string _personnalites_people_id:integer _personnalites_people_plus_id:integer comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _petites_annonces_section name
rails g scaffold _petites_annonces_pays name
rails g scaffold _petites_annonces_lieu name
rails g scaffold _petites_annonces type:string type:string titre:string image:string _petites_annonces_section_id:integer etat_produit:string etat_produit:string etat_produit:string etat_produit:string etat_produit:string _petites_annonces_pays_id:integer _petites_annonces_lieu_id:integer prix:string description:text statut:string statut:string comment:text acceptregles:string
rails g scaffold _recettes_type name
rails g scaffold _recettes_plat name
rails g scaffold _recettes_difficulte name
rails g scaffold _recettes nom:string _recettes_type_id:integer image:string preparation:string cuisson:string nb_pers:string _recettes_plat_id:integer _recettes_difficulte_id:integer ingredients:text texte:text source:string comment:text acceptregles:string
rails g scaffold _restaurants_pays name
rails g scaffold _restaurants nom:string image:string adresse:text tel:string description:text dept:string ville:string _restaurants_pays_id:integer horaires:text creation:string site:string acceptregles:string
rails g scaffold _sites_dachats_pays name
rails g scaffold _sites_dachats nom:string url:string description:text _sites_dachats_pays_id:integer acceptregles:string
rails g scaffold _tablatures_people name
rails g scaffold _tablatures_people name
rails g scaffold _tablatures titre:string _tablatures_people_id:integer _tablatures_people_id:integer infos:text comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _videos_id_cat name
rails g scaffold _videos titre:string _videos_id_cat_id:integer url:string tags:string
rails g scaffold _volumes_ln name
rails g scaffold _volumes_type name
rails g scaffold _volumes_illustrations name
rails g scaffold _volumes _volumes_ln_id:integer numero:string _volumes_type_id:integer numerique:string image:string image_nc:string image_vo:string image_vo2:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string prix:string prix_vo:string pages:string _volumes_illustrations_id:integer ean:string relie:string sous_jaquette:string resume:text chapitres:text infos:text preview:string comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold _volumes_manga name
rails g scaffold _volumes_type name
rails g scaffold _volumes_illustrations name
rails g scaffold _volumes _volumes_manga_id:integer numero:string _volumes_type_id:integer numerique:string image:string image_nc:string image_vo:string image_vo2:string date_parution_vo_jj:string date_parution_vo_mm:string date_parution_vo_aaaa:string date_parution_vf_jj:string date_parution_vf_mm:string date_parution_vf_aaaa:string prix:string prix_vo:string pages:string _volumes_illustrations_id:integer ean:string relie:string sous_jaquette:string resume:text chapitres:text infos:text preview:string comment:text statut_prop:string statut_prop:string acceptregles:string
rails g scaffold amvs_makers name
rails g scaffold amvs_makers name
rails g scaffold amvs_type name
rails g scaffold amvs_type name
rails g scaffold amvs_conventions name
rails g scaffold amvs_conventions name
rails g scaffold amvs_groupes name
rails g scaffold amvs_anime name
rails g scaffold amvs_jv name
rails g scaffold amvs_amv name
rails g scaffold amvs titre:string image:string amvs_makers_id:integer amvs_makers_id:integer youtube:string lien:string song:text date_jj:string date_mm:string date_aaaa:string duree:string amvs_type_id:integer amvs_type_id:integer description:text amvs_conventions_id:integer amvs_conventions_id:integer amvs_groupes_id:integer amvs_anime_id:integer amvs_jv_id:integer amvs_amv_id:integer autre:string comment:text statut_prop:string statut_prop:string acceptregles:string
