Rails.application.routes.draw do
  resources :amvs
  resources :amvs_amvs
  resources :amvs_jvs
  resources :amvs_animes
  resources :amvs_groupes
  resources :amvs_conventions
  resources :amvs_types
  resources :amvs_makers
  resources :volumes_mangas
  resources :volumes
  resources :volumes_illustrations
  resources :volumes_types
  resources :volumes_lns
  resources :videos
  resources :videos_id_cats
  resources :tablatures
  resources :tablatures_people
  resources :sites_dachats
  resources :sites_dachats_pays
  resources :restaurants
  resources :restaurants_pays
  resources :recettes
  resources :recettes_difficultes
  resources :recettes_plats
  resources :recettes_types
  resources :petites_annonces
  resources :petites_annonces_lieus
  resources :petites_annonces_pays
  resources :petites_annonces_sections
  resources :personnalites
  resources :personnalites_people_plus
  resources :personnalites_people
  resources :personnalites_id_travauxes
  resources :personnalites_id_galeries
  resources :personnalites_ex_fins
  resources :personnalites_ex_debuts
  resources :personnalites_exes
  resources :personnalites_id_membres
  resources :personnalites_roles
  resources :personnalites_agences_exes
  resources :personnalites_agences_fins
  resources :personnalites_agences_debuts
  resources :personnalites_agences
  resources :personnalites_labels_exes
  resources :personnalites_labels_fins
  resources :personnalites_labels_debuts
  resources :personnalites_labels
  resources :personnalites_genres
  resources :personnalites_statuts
  resources :personnalites_pays
  resources :personnalites_sexes
  resources :personnalites_type_people
  resources :personnage_de_mangas
  resources :personnage_de_mangas_goodies
  resources :personnage_de_mangas_jv_persos
  resources :personnage_de_mangas_perso_plus
  resources :personnage_de_mangas_persos
  resources :personnage_de_mangas_perso_mangas
  resources :personnage_de_mangas_mangas
  resources :personnages_de_jeux_videos
  resources :personnages_de_jeux_videos_goodies
  resources :personnages_de_jeux_videos_perso_mangas
  resources :personnages_de_jeux_videos_perso_plus
  resources :personnages_de_jeux_videos_persos
  resources :personnages_de_jeux_videos_jv_persos
  resources :personnages_de_jeux_videos_doubleur_roles
  resources :personnages_de_jeux_videos_doubleur_people
  resources :personnages_de_jeux_videos_doubleur_pays
  resources :personnages_de_jeux_videos_jvs
  resources :personnage_danimes
  resources :personnage_danimes_goodies
  resources :personnage_danimes_jv_persos
  resources :personnage_danimes_perso_mangas
  resources :personnage_danimes_perso_plus
  resources :personnage_danimes_persos
  resources :personnage_danimes_doubleur_roles
  resources :personnage_danimes_doubleur_people
  resources :personnage_danimes_doubleur_pays
  resources :personnage_danimes_animes
  resources :personnage_danimes_sexes
  resources :paroles
  resources :paroles_paroles
  resources :paroles_staff_people
  resources :paroles_staff_roles
  resources :numero_demission_tvs
  resources :numero_demission_tvs_clips
  resources :numero_demission_tvs_emission_tv_numeros
  resources :numero_demission_tvs_people
  resources :numero_demission_tvs_presentateurs
  resources :numero_demission_tvs_specials
  resources :numero_demission_tvs_id_emission_tvs
  get "/planning/manga", to: "mangas#planning"
  resources :mangas do
    collection do
      get "planning"
    end
  end
  resources :mangas_clips
  resources :mangas_people
  resources :mangas_concours
  resources :mangas_quizzs
  resources :mangas_sondages
  resources :mangas_actualite_minis
  resources :mangas_cultures
  resources :mangas_actualites
  resources :mangas_artbooks
  resources :mangas_litterature_asiatique_plus
  resources :mangas_litterature_asiatiques
  resources :mangas_am_plus
  resources :mangas_ams
  resources :mangas_jv_plus
  resources :mangas_jvs
  resources :mangas_drama_plus
  resources :mangas_dramas
  resources :mangas_manga_plus
  resources :mangas_mangas
  resources :mangas_ln_plus
  resources :mangas_lns
  resources :mangas_anime_plus
  resources :mangas_animes
  resources :mangas_groupes
  resources :mangas_commerces
  resources :mangas_public_avertis
  resources :mangas_societe_people
  resources :mangas_societe_roles
  resources :mangas_staff_people
  resources :mangas_staff_roles
  resources :mangas_prepublies
  resources :mangas_editeurs_vf_collections
  resources :mangas_editeurs_vfs
  resources :mangas_editeurs_vos
  resources :mangas_encours_vfs
  resources :mangas_encours_vos
  resources :mangas_themes
  resources :mangas_genres
  resources :mangas_types
  resources :mangas_pays
  resources :livres
  resources :livres_jv_plus
  resources :livres_jvs
  resources :livres_people
  resources :livres_actualite_minis
  resources :livres_cultures
  resources :livres_actualites
  resources :livres_goodies
  resources :livres_litterature_asiatique_plus
  resources :livres_litterature_asiatiques
  resources :livres_am_plus
  resources :livres_ams
  resources :livres_drama_plus
  resources :livres_dramas
  resources :livres_manga_plus
  resources :livres_mangas
  resources :livres_ln_plus
  resources :livres_lns
  resources :livres_anime_plus
  resources :livres_animes
  resources :livres_groupes
  resources :livres_public_avertis
  resources :livres_pays_themes
  resources :livres_themes
  resources :livres_genres
  resources :livres_editeurs_vfs
  resources :livres_editeurs_vos
  resources :livres_staff_people
  resources :livres_staff_roles
  resources :livres_statut_publications
  resources :livres_pays
  resources :livres_type_secondaires
  resources :livres_types
  resources :light_novels
  resources :light_novels_quizzs
  resources :light_novels_actualite_minis
  resources :light_novels_cultures
  resources :light_novels_actualites
  resources :light_novels_artbooks
  resources :light_novels_osts
  resources :light_novels_litterature_asiatique_plus
  resources :light_novels_litterature_asiatiques
  resources :light_novels_am_plus
  resources :light_novels_ams
  resources :light_novels_jv_plus
  resources :light_novels_jvs
  resources :light_novels_drama_plus
  resources :light_novels_dramas
  resources :light_novels_ln_plus
  resources :light_novels_lns
  resources :light_novels_manga_plus
  resources :light_novels_mangas
  resources :light_novels_anime_plus
  resources :light_novels_animes
  resources :light_novels_groupes
  resources :light_novels_commerces
  resources :light_novels_public_avertis
  resources :light_novels_societe_people
  resources :light_novels_societe_roles
  resources :light_novels_staff_people
  resources :light_novels_staff_roles
  resources :light_novels_prepublies
  resources :light_novels_editeurs_vf_collections
  resources :light_novels_editeurs_vfs
  resources :light_novels_editeurs_vos
  resources :light_novels_encours_vfs
  resources :light_novels_encours_vos
  resources :light_novels_themes
  resources :light_novels_genres
  resources :light_novels_pays
  resources :jeux_videos, path:"jeuxvideo"
  resources :jeux_videos_topics
  resources :jeux_videos_people
  resources :jeux_videos_concours
  resources :jeux_videos_quizzs
  resources :jeux_videos_sondages
  resources :jeux_videos_amvs
  resources :jeux_videos_doujins
  resources :jeux_videos_cds
  resources :jeux_videos_osts
  resources :jeux_videos_cultures
  resources :jeux_videos_litterature_asiatique_plus
  resources :jeux_videos_litterature_asiatiques
  resources :jeux_videos_artbooks
  resources :jeux_videos_dvds
  resources :jeux_videos_univers
  resources :jeux_videos_drama_plus
  resources :jeux_videos_dramas
  resources :jeux_videos_am_plus
  resources :jeux_videos_ams
  resources :jeux_videos_jv_plus
  resources :jeux_videos_jvs
  resources :jeux_videos_manga_plus
  resources :jeux_videos_mangas
  resources :jeux_videos_ln_plus
  resources :jeux_videos_lns
  resources :jeux_videos_anime_plus
  resources :jeux_videos_animes
  resources :jeux_videos_actualite_minis
  resources :jeux_videos_actualites
  resources :jeux_videos_groupes
  resources :jeux_videos_staff_people
  resources :jeux_videos_staff_roles
  resources :jeux_videos_staff_societes
  resources :jeux_videos_staff_societe_roles
  resources :jeux_videos_genres
  resources :jeux_videos_themes
  resources :jeux_videos_etats
  resources :jeux_videos_pays
  resources :jeux_videos_pays_dates
  resources :jeux_videos_plateformes
  resources :generiques
  resources :generiques_generics
  resources :generiques_staff_people
  resources :generiques_staff_roles
  resources :generiques_types
  resources :generiques_id_animes
  resources :generique_de_jeu_videos
  resources :generique_de_jeu_videos_jv_generics
  resources :generique_de_jeu_videos_jvs
  resources :generique_de_jeu_videos_staff_people
  resources :generique_de_jeu_videos_staff_roles
  resources :generique_de_jeu_videos_types
  resources :films_asiatiques
  resources :films_asiatiques_artbooks
  resources :films_asiatiques_dvds
  resources :films_asiatiques_concours
  resources :films_asiatiques_quizzs
  resources :films_asiatiques_sondages
  resources :films_asiatiques_cds
  resources :films_asiatiques_doujins
  resources :films_asiatiques_osts
  resources :films_asiatiques_actualite_minis
  resources :films_asiatiques_emission_tv_plus
  resources :films_asiatiques_emission_tvs
  resources :films_asiatiques_cultures
  resources :films_asiatiques_actualites
  resources :films_asiatiques_litterature_asiatique_plus
  resources :films_asiatiques_litterature_asiatiques
  resources :films_asiatiques_people
  resources :films_asiatiques_univers
  resources :films_asiatiques_cinemas
  resources :films_asiatiques_am_plus
  resources :films_asiatiques_ams
  resources :films_asiatiques_jv_plus
  resources :films_asiatiques_jvs
  resources :films_asiatiques_drama_plus
  resources :films_asiatiques_dramas
  resources :films_asiatiques_manga_plus
  resources :films_asiatiques_mangas
  resources :films_asiatiques_ln_plus
  resources :films_asiatiques_lns
  resources :films_asiatiques_anime_plus
  resources :films_asiatiques_animes
  resources :films_asiatiques_groupes
  resources :films_asiatiques_generiques_paroles
  resources :films_asiatiques_generiques_clips
  resources :films_asiatiques_generiques_people2s
  resources :films_asiatiques_generiques_people
  resources :films_asiatiques_generiques_types
  resources :films_asiatiques_editeurs_vfs
  resources :films_asiatiques_editeurs_vf_roles
  resources :films_asiatiques_acteurs
  resources :films_asiatiques_types
  resources :films_asiatiques_societe_people
  resources :films_asiatiques_societe_roles
  resources :films_asiatiques_staff_people
  resources :films_asiatiques_staff_roles
  resources :films_asiatiques_themes
  resources :films_asiatiques_genres
  resources :films_asiatiques_pays
  resources :films_asiatiques_origines
  resources :films_asiatiques_en_salles
  resources :films_asiatiques_en_salles_actualite_minis
  resources :films_asiatiques_en_salles_actualites
  resources :films_asiatiques_en_salles_dramas
  resources :films_asiatiques_en_salles_ams
  resources :films_asiatiques_en_salles_animes
  resources :films_asiatiques_en_salles_acteurs
  resources :films_asiatiques_en_salles_types
  resources :films_asiatiques_en_salles_staff_people
  resources :films_asiatiques_en_salles_staff_roles
  resources :films_asiatiques_en_salles_genres
  resources :films_asiatiques_en_salles_pays_origines
  resources :films_asiatiques_en_salles_langues
  resources :films_asiatiques_en_salles_pays
  resources :fiche_univers
  resources :fiche_univers_cultures
  resources :fiche_univers_actualite_minis
  resources :fiche_univers_actualites
  resources :fiche_univers_people
  resources :fiche_univers_litterature_asiatiques
  resources :fiche_univers_ams
  resources :fiche_univers_dramas
  resources :fiche_univers_jv_persos
  resources :fiche_univers_jvs
  resources :fiche_univers_doujinshis
  resources :fiche_univers_lns
  resources :fiche_univers_perso_mangas
  resources :fiche_univers_mangas
  resources :fiche_univers_persos
  resources :fiche_univers_animes
  resources :fiche_univers_univers
  resources :fiche_univers_groupes
  resources :fiche_univers_cats
  resources :dramas
  resources :dramas_emission_tv_plus
  resources :dramas_emission_tvs
  resources :dramas_artbooks
  resources :dramas_dvds
  resources :dramas_cds
  resources :dramas_doujins
  resources :dramas_osts
  resources :dramas_actualite_minis
  resources :dramas_cultures
  resources :dramas_actualites
  resources :dramas_litterature_asiatique_plus
  resources :dramas_litterature_asiatiques
  resources :dramas_univers
  resources :dramas_am_plus
  resources :dramas_ams
  resources :dramas_jv_plus
  resources :dramas_jvs
  resources :dramas_drama_plus
  resources :dramas_dramas
  resources :dramas_manga_plus
  resources :dramas_mangas
  resources :dramas_ln_plus
  resources :dramas_lns
  resources :dramas_anime_plus
  resources :dramas_animes
  resources :dramas_groupes
  resources :dramas_generiques_paroles
  resources :dramas_generiques_clips
  resources :dramas_generiques_people2s
  resources :dramas_generiques_people
  resources :dramas_generiques_types
  resources :dramas_programmes
  resources :dramas_editeurs_vfs
  resources :dramas_editeurs_vf_roles
  resources :dramas_acteurs
  resources :dramas_types
  resources :dramas_societe_people
  resources :dramas_societe_roles
  resources :dramas_staff_people
  resources :dramas_staff_roles
  resources :dramas_themes
  resources :dramas_genres
  resources :dramas_pays
  resources :dramas_encours
  resources :dramas_origines
  resources :doujinshis
  resources :doujinshis_people
  resources :doujinshis_quizzs
  resources :doujinshis_jv_persos
  resources :doujinshis_perso_mangas
  resources :doujinshis_perso_plus
  resources :doujinshis_persos
  resources :doujinshis_actualite_minis
  resources :doujinshis_cultures
  resources :doujinshis_actualites
  resources :doujinshis_artbooks
  resources :doujinshis_litterature_asiatique_plus
  resources :doujinshis_litterature_asiatiques
  resources :doujinshis_am_plus
  resources :doujinshis_ams
  resources :doujinshis_jv_plus
  resources :doujinshis_jvs
  resources :doujinshis_drama_plus
  resources :doujinshis_dramas
  resources :doujinshis_doujinshi_plus
  resources :doujinshis_doujinshis
  resources :doujinshis_ln_plus
  resources :doujinshis_lns
  resources :doujinshis_manga_plus
  resources :doujinshis_mangas
  resources :doujinshis_anime_plus
  resources :doujinshis_animes
  resources :doujinshis_groupes
  resources :doujinshis_gratuits
  resources :doujinshis_censures
  resources :doujinshis_public_avertis
  resources :doujinshis_staff_people
  resources :doujinshis_roles
  resources :doujinshis_conventions
  resources :doujinshis_genres_avertis
  resources :doujinshis_themes
  resources :doujinshis_genres
  resources :doujinshis_types
  resources :doujinshis_pays
  resources :doujinshis_origines
  resources :doujinshis_frances
  resources :doujins
  resources :doujins_artbooks
  resources :doujins_doujins
  resources :doujins_jvs
  resources :doujins_ams
  resources :doujins_dramas
  resources :doujins_lns
  resources :doujins_animes
  resources :doujins_groupes
  resources :doujins_genres
  resources :doujins_people
  resources :doujins_roles
  resources :doujins_conventions
  resources :concerts_pays
  resources :concerts_artistes
  get "concert",to:"clips/lives/bonus/concerts#index"
  get "concerts",to:"clips/lives/bonus/concerts#agenda"
  get "cinema",to:"films_asiatiques_en_salles#agenda"
  namespace :clips do
    namespace :lives do
      namespace :bonus do
        resources :concerts
        resources :concerts_emission_tv_numeros
        resources :concerts_clips
        resources :concerts_people
        resources :concerts_roles
        resources :concerts_type_bonus
        resources :concerts_types
      end
    end
  end

  resources :breves_cultures
  resources :breves_societes
  resources :breves_jv_societes
  resources :breves_anime_studios
  resources :breves_manga_editeurs
  resources :breves_concours
  resources :breves_quizzs
  resources :breves_sondages
  resources :breves_emission_tv_numeros
  resources :breves_emission_tvs
  resources :breves_clips
  resources :breves_amvs
  resources :breves_osts
  resources :breves_cds
  resources :breves_recettes
  resources :breves_concerts
  resources :breves_evenements
  resources :breves_cinemas
  resources :breves_goodies
  resources :breves_photobooks
  resources :breves_artbooks
  resources :breves_dvds
  resources :breves_jvs
  resources :breves_beau_livres
  resources :breves_magazines
  resources :breves_livre_jeunesses
  resources :breves_litterature_asiatiques
  resources :breves_ams
  resources :breves_dramas
  resources :breves_mangas
  resources :breves_lns
  resources :breves_animes
  resources :breves_people
  resources :breves_actualite_minis
  resources :breves_actualites
  resources :breves_cats
  resources :breves, controller: "breves", path: "breves"
  resources :boutiques
  resources :boutiques_pays
  resources :photobooks
  resources :photobooks_goodies
  resources :photobooks_actualite_minis
  resources :photobooks_actualites
  resources :photobooks_bonus
  resources :photobooks_animes
  resources :photobooks_photobooks
  resources :photobooks_cds
  resources :photobooks_ams
  resources :photobooks_dramas
  resources :photobooks_groupes
  resources :photobooks_public_avertis
  resources :photobooks_societe_people
  resources :photobooks_societe_roles
  resources :photobooks_people
  resources :photobooks_roles
  resources :photobooks_editeurs_vfs
  resources :photobooks_editeurs_vos
  resources :photobooks_types
  resources :photobooks_illustrations
  resources :photobooks_disponibilites
  resources :photobooks_pays
  resources :photobooks_frances
  resources :goodies
  resources :goodies_actualite_minis
  resources :goodies_actualites
  resources :goodies_litterature_asiatiques
  resources :goodies_bonus
  resources :goodies_clips
  resources :goodies_goodies
  resources :goodies_people
  resources :goodies_osts
  resources :goodies_cds
  resources :goodies_dvds
  resources :goodies_doujinshis
  resources :goodies_photobooks
  resources :goodies_artbooks
  resources :goodies_ams
  resources :goodies_dramas
  resources :goodies_lns
  resources :goodies_jv_persos
  resources :goodies_jvs
  resources :goodies_perso_mangas
  resources :goodies_mangas
  resources :goodies_persos
  resources :goodies_animes
  resources :goodies_groupes
  resources :goodies_public_avertis
  resources :goodies_societe_people
  resources :goodies_societe_roles
  resources :goodies_staff_people
  resources :goodies_staff_roles
  resources :goodies_editeurs_vfs
  resources :goodies_editeurs_vos
  resources :goodies_matieres
  resources :goodies_pays
  resources :goodies_types
  get "dvd-blu-ray", to:"dvd/blu_rays#index"

  namespace :dvd do
    resources :blu_rays
    resources :blu_rays_actualite_minis
    resources :blu_rays_actualites
    resources :blu_rays_emission_tvs
    resources :blu_rays_people
    resources :blu_rays_jvs
    resources :blu_rays_litterature_asiatiques
    resources :blu_rays_ams
    resources :blu_rays_dramas
    resources :blu_rays_animes
    resources :blu_rays_groupes
    resources :blu_rays_public_avertis
    resources :blu_rays_editeurs
    resources :blu_rays_type_editions
    resources :blu_rays_formats
    resources :blu_rays_pays
    resources :blu_rays_frances
  end
  resources :cds
  resources :cds_mangas
  resources :cds_bonus
  resources :cds_emission_tvs
  resources :cds_jvs
  resources :cds_ams
  resources :cds_dramas
  resources :cds_lns
  resources :cds_animes
  resources :cds_cds
  resources :cds_groupes
  resources :cds_distributeurs
  resources :cds_labels
  resources :cds_people
  resources :cds_roles
  resources :cds_monnaies
  resources :cds_types
  resources :artbooks
  resources :artbooks_cultures
  resources :artbooks_actualite_minis
  resources :artbooks_actualites
  resources :artbooks_doujins
  resources :artbooks_goodies
  resources :artbooks_artbooks
  resources :artbooks_litterature_asiatiques
  resources :artbooks_ams
  resources :artbooks_dramas
  resources :artbooks_jvs
  resources :artbooks_doujinshis
  resources :artbooks_lns
  resources :artbooks_mangas
  resources :artbooks_animes
  resources :artbooks_groupes
  resources :artbooks_public_avertis
  resources :artbooks_societe_people
  resources :artbooks_societe_roles
  resources :artbooks_people
  resources :artbooks_roles
  resources :artbooks_editeurs_vfs
  resources :artbooks_editeurs_vos
  resources :artbooks_types
  resources :artbooks_illustrations
  resources :artbooks_pays
  resources :artbooks_frances
  resources :evenements
  resources :evenements_people
  resources :evenements_pays

  get "/animes/:saispn-:annee", to: "animes#saison"
  resources :animes do
    collection do
      get "planning", to:"animes#planning"
    end
  end
  get "/persos", to:"personnage_danimes#index"
  get "/lyrics",to:"generiques#index"
  get "/amv",to:"amvs#index"

  resources :animes_topics
  resources :animes_quizzs
  resources :animes_cinemas
  resources :animes_amvs
  resources :animes_doujins
  resources :animes_cds
  resources :animes_osts
  resources :animes_cultures
  resources :animes_litterature_asiatique_plus
  resources :animes_litterature_asiatiques
  resources :animes_photobooks
  resources :animes_artbooks
  resources :animes_dvds
  resources :animes_people
  resources :animes_drama_plus
  resources :animes_dramas
  resources :animes_am_plus
  resources :animes_ams
  resources :animes_jv_plus
  resources :animes_jvs
  resources :animes_manga_plus
  resources :animes_mangas
  resources :animes_ln_plus
  resources :animes_lns
  resources :animes_anime_plus
  resources :animes_animes
  resources :animes_actualite_minis
  resources :animes_actualites
  resources :animes_groupes
  resources :animes_editeurs_vfs
  resources :animes_editeurs_vf_roles
  resources :animes_public_avertis
  resources :animes_societe_people
  resources :animes_societe_roles
  resources :animes_staff_people
  resources :animes_staff_roles
  resources :animes_themes
  resources :animes_genres
  resources :animes_pays
  resources :animes_encours
  resources :animes_origines
  resources :animes_formats
  resources :osts
  resources :osts_emission_tvs
  resources :osts_osts
  resources :osts_jvs
  resources :osts_ams
  resources :osts_dramas
  resources :osts_lns
  resources :osts_animes
  resources :osts_groupes
  resources :osts_distributeurs
  resources :osts_labels
  resources :osts_people
  resources :osts_roles
  resources :osts_monnaies
  resources :osts_plateformes
  resources :osts_types
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end
